Implement GUI protocol 1.4
QubesOS/qubes-gui-daemon pull request #105
Opened 2022-07-06 13:51 UTC by DemiMarie

This allows bidirectional protocol negotiation, which means that the
agent can be newer than the daemon.

The daemon must be upgraded to support protocol 1.4 first.  Afterwards,
agents and daemons can be independently upgraded.

2022-07-08 00:52 UTC, marmarek requested changes

2022-07-08 00:52 UTC, marmarek commented on gui-daemon/xside.c
> +    } conf;
There is no need to send those two messages at once, please use separate write (and no wrapping struct).

2022-07-08 00:52 UTC, marmarek commented on gui-daemon/xside.c
> +    if (protocol_version_at_least(g, 1, 4)) {
That's a lot of code for `g->protocol_version >= 0x00010004U` (it may be worth to have a macro for combining them, and maybe even a `#define` somewhere for this specific version value, as the point of changing negotiation).

2022-07-08 01:35 UTC, DemiMarie commented on gui-daemon/xside.c
> +    } conf;
Sending them at once is a teeny bit faster, but I admit that the loss in maintainability probably is not worthwhile.

2022-07-08 01:35 UTC, DemiMarie commented on gui-daemon/xside.c
> +    if (protocol_version_at_least(g, 1, 4)) {
Are you referring to the `protocol_version_at_least` inline function?  To me, that is quite a bit clearer than `g->protocol_version >= 0x00010004U`, and it only needs to be written once.

2022-07-08 01:40 UTC, marmarek commented on gui-daemon/xside.c
> +    if (protocol_version_at_least(g, 1, 4)) {
Yes, having a function to perform just `>=` hides what it actually is.
```
#define GUI_PROTOCOL(major, minor) ((major) << 16 | (minor))
...
if (g->protocol_version >= GUI_PROTOCOL_VERSION(1, 4)) {
```

2022-07-08 07:28 UTC, DemiMarie commented
Build is broken because this has a hard dependency on QubesOS/qubes-gui-common#16.

2022-07-18 18:50 UTC, DemiMarie commented
@locriacyber The problem with this is that it requires support from both daemon and agent, and right now neither have such support.  Therefore, there needs to be _some_ way to announce support for this.  Also, having to deal with all possible feature bits is a testing nightmare.  Just having to deal with all the different version combinations will be hard enough.

2022-07-19 23:00 UTC, marmarek requested changes

2022-07-19 23:00 UTC, marmarek commented on gui-daemon/xside.h
> +    uint32_t protocol_version;  /* gui-agent (protocol) version */
Comment needs updating - it isn't just agent version anymore, it is negotiated protocol version (which may be older than the agent's one).

2022-07-20 02:22 UTC, marmarek approved these changes

2022-07-20 02:23 UTC, merged

2022-07-20 21:46 UTC, marmarek commented
> Since newer clients will not work with older server.

Yes, but older clients will work with newer server.