Fix pacat-simple-vchan
QubesOS/qubes-gui-daemon pull request #109
Opened 2022-07-15 04:45 UTC by DemiMarie

This fixes multiple bugs in pacat-simple-vchan.  See individual commit messages for details.

2022-07-15 10:18 UTC, DemiMarie commented
PipelineRefresh

2022-07-15 13:10 UTC, DemiMarie commented
I tested this, and it works.  However, when used with the standard (PulseAudio) agent, it introduces glitches that were not present previously.  I believe the culprit is the standard agent’s small buffer sizes, which lead to overruns.  The PipeWire agent avoids this by using larger buffers.

2022-07-20 00:59 UTC, marmarek requested changes

2022-07-21 00:23 UTC, marmarek commented on pulse/pacat-simple-vchan.c
> +    if (rec_buffer_length > (size_t)vchan_buffer_space) {
Is it guaranteed to _not_ trigger in normal usage (empty or almost-empty buffer)? IOW, is pulseaudio aware to send data in chunks smaller than 2048 bytes?

2022-07-21 01:22 UTC, DemiMarie commented on pulse/pacat-simple-vchan.c
> +    if (rec_buffer_length > (size_t)vchan_buffer_space) {
With the current buffer sizes, this triggers quite frequently in my tests.  That said, the intent is to solve this by increasing the vchan buffer size (QubesOS/qubes-gui-agent-linux#164).  Should I handle it instead by buffering in this program?

2022-07-21 05:59 UTC, DemiMarie commented on pulse/pacat-simple-vchan.c
> +    if (rec_buffer_length > (size_t)vchan_buffer_space) {
Good news: with a buffer size of 1 << 15 I get no overruns.

2022-07-24 11:35 UTC, marmarek requested changes

2022-07-24 11:35 UTC, marmarek commented on pulse/pacat-simple-vchan.c
> +    if ((l=libvchan_send(u->rec_ctrl, rec_buffer, rec_buffer_length)) < 0) {
It should remain `libvchan_write`, otherwise you still break the old version (if vchan buffer is smaller than `rec_buffer_length`, it will never send anything). Furthermore, if `!u->never_block`, I think it should still loop over the whole buffer, not just attempt once.

2022-07-24 11:36 UTC, marmarek commented
All recording tests failed with "only silence detected, no useful audio data". I guess that's because of the change I commented above.

2022-07-25 06:03 UTC, DemiMarie commented
New version pushed, but not tested.

2022-07-25 23:21 UTC, DemiMarie commented
Works for me with the stock PulseAudio module.

2022-07-26 11:00 UTC, marmarek requested changes

2022-07-26 11:00 UTC, marmarek commented on pulse/pacat-simple-vchan.c
> +        if (u->never_block && rec_buffer_length > (size_t)vchan_buffer_space) {
`u->never_block` is always true in this branch

2022-07-26 11:00 UTC, marmarek commented on pulse/pacat-simple-vchan.c
>          /* can block */
update comment?

2022-07-27 01:51 UTC, DemiMarie commented
PipelineRetryFailed

2022-08-06 16:20 UTC, locriacyber commented
this unnecessarily depend on glib-2.0

2022-08-30 10:15 UTC, marmarek approved these changes

2022-08-30 10:23 UTC, merged