No sysv shm
QubesOS/qubes-gui-daemon pull request #116
Opened 2022-08-13 02:25 UTC by DemiMarie

2022-08-30 10:16 UTC, marmarek commented
Duplicate of https://github.com/QubesOS/qubes-gui-daemon/pull/78 ?

2022-08-30 20:02 UTC, DemiMarie commented
> Duplicate of #78 ?

Same as #78 but with a few extra commits.

2022-10-13 02:43 UTC, marmarek requested changes

2022-10-13 02:43 UTC, marmarek commented on shmoverride/shmoverride.c
> +#ifdef NDEBUG
The usual comment.

2022-10-13 15:56 UTC, DemiMarie commented on shmoverride/shmoverride.c
> +                    break;
It is necessary inasmuch as `strtoul` is a bit too loose (it accepts leading whitespace and other junk).  We should really have a utility function for this.

2022-10-13 16:13 UTC, marmarek commented on shmoverride/shmoverride.c
> +                    break;
I have the opposite opinion: it's okay to accept more flexible format on command line (which again, is a trusted input, you don't need to be strict here).

2022-10-13 18:56 UTC, marmarek commented on shmoverride/shmoverride.c
> +                    break;
In this particular place, it's more important to behave similar to Xorg, than to be strict. The Xorg version is here: https://github.com/freedesktop/xorg-xserver/blob/master/os/utils.c#L606-L646

In particular, it does allow `:0.0` or similar which your function refuses.

2022-10-13 20:16 UTC, DemiMarie commented on shmoverride/shmoverride.c
> +                    break;
Good point.  Now fixed, along with some other bugs (such as not handling `-I` and not skipping `argv[0]`).

2022-10-13 22:22 UTC, marmarek requested changes

2022-10-13 22:22 UTC, marmarek commented on shmoverride/shmoverride.c
> +/* FIXME: should be in a utility library */
There is one already: standard `isdigit()`. It is used in the code I linked you before...

2022-10-13 22:38 UTC, DemiMarie commented on shmoverride/shmoverride.c
> +/* FIXME: should be in a utility library */
Done, though note that `isdigit()` can be locale-dependent and so it often is not what one wants.

2022-10-15 17:02 UTC, marmarek approved these changes

2022-10-15 17:04 UTC, merged