Fix function prototype mismatches and use poll(2)
QubesOS/qubes-gui-daemon pull request #117
Opened 2022-08-30 19:59 UTC by DemiMarie

This fixes function prototype mismatches (caught using
-Wmissing-prototypes) and replaces select(2) with poll(2).  No change in
behavior.

2022-10-13 02:53 UTC, marmarek requested changes

2022-10-13 02:53 UTC, marmarek commented on gui-common/txrx-vchan.c
> +        { .fd = fd, .events = POLLIN | POLLRDHUP | POLLPRI, .revents = 0 },
This is change in behavior - the `select()` version put the fd only in `readfds` set, _not_ `exceptfds`. Please keep the old behavior (just `POLLIN`), unless there is some specific reason for the change.

2022-10-16 02:30 UTC, marmarek commented
Now this one needs rebase...

2022-10-16 02:50 UTC, DemiMarie commented
And rebased.

2022-10-16 03:59 UTC, DemiMarie commented
PipelineRetryFailed

2022-10-19 00:26 UTC, marmarek approved these changes

2022-10-19 00:27 UTC, merged