do_shm_update: Negative width or height is an error
QubesOS/qubes-gui-daemon pull request #123
Opened 2022-10-15 19:00 UTC by DemiMarie

Negative width or height makes no sense.  Treat this as an error condition.  This allows simplifying the rest of do_shm_update(), as this corner case no longer needs to be checked for.

2022-11-01 20:10 UTC, DemiMarie commented
PipelineRetryFailed

2023-01-09 18:50 UTC, marmarek requested changes

2023-01-09 18:50 UTC, marmarek commented on gui-daemon/xside.c
> +    int32_t x = 0, y = 0, w = 0, h = 0;
I don't like this (and other in this PR) narrowing variables. It makes things more likely to explode if any of the reasoning below is incorrect (and also makes this reasoning more tricky, as for example adding two 32-bit values is no longer always-safe).

So, to this whole PR: refusing negative sizes early - okay, narrowing types - not.

2023-01-09 19:08 UTC, DemiMarie commented on gui-daemon/xside.c
> +    int32_t x = 0, y = 0, w = 0, h = 0;
I’m confused by what you mean by “narrowing types”.  `int32_t` is just a typedef for `int` on x86_64, so replacing `int` with `int32_t` is a no-op.  If you mean the `(int32_t)` casts, those are to suppress `-Wsign-conversion` and friends.  That said, those should be a separate PR.

2023-01-21 15:59 UTC, marmarek approved these changes

2023-02-28 13:39 UTC, merged