Allow periods in qube names
QubesOS/qubes-gui-daemon pull request #132
Opened 2023-06-03 01:25 UTC by DemiMarie

This allows periods in qube names by using the function from libqubes-pure to validate them instead of the built-in version.

Part of QubesOS/qubes-issues#8199.

2023-08-05 20:03 UTC, marmarek commented
PipelineRetry

2023-08-06 01:57 UTC, marmarek requested changes
This fails to build due to not linking with libqubes-pure.

2023-08-06 01:57 UTC, marmarek commented on debian/control
> + qubes-utils-dev (>= 4.2.10)
There is no such package. It seems you put it into `libqubes-rpc-filecopy-dev`.

2023-08-06 17:12 UTC, DemiMarie commented on debian/control
> + qubes-utils-dev (>= 4.2.10)
Should I change that?  `libqubes-rpc-filecopy-dev` is obviously wrong.

2023-08-06 18:29 UTC, marmarek commented on debian/control
> + qubes-utils-dev (>= 4.2.10)
The proper Debian way would be a new subpackage. I think we don't link against that library anywhere yet (this is the first PR doing it, so it's still ok to fix packaging there.

2023-08-06 22:08 UTC, DemiMarie commented on debian/control
> + qubes-utils-dev (>= 4.2.10)
I’m pretty sure that qfile-unpacker links to libqubes-pure already.

2023-08-07 01:50 UTC, marmarek commented on debian/control
> + qubes-utils-dev (>= 4.2.10)
But fortunately, not directly, but through a library that is also in linux-utils, so splitting the package should still be safe-ish. If you want, I can do it, and try to setup dependencies properly.

2023-08-07 16:11 UTC, DemiMarie commented on debian/control
> + qubes-utils-dev (>= 4.2.10)
That would be great, thanks.

2023-08-20 02:25 UTC, marmarek commented on debian/control
> + qubes-utils-dev (>= 4.2.10)
Package is split, you can adjust dependency now.

2023-09-10 23:05 UTC, marmarek approved these changes

2023-09-11 15:33 UTC, merged