new device API
QubesOS/qubes-gui-daemon pull request #139
Opened 2024-02-06 17:27 UTC by piotrbartman

after QubesOS/qubes-core-admin/pull/579

2024-03-15 00:37 UTC, marmarek approved these changes

2024-03-29 20:21 UTC, marmarek requested changes

2024-03-29 20:21 UTC, marmarek commented on qubesguidaemon/mic.py
> +class MicDevice(qubes.device_protocol.DeviceInfo):
Missing `qubes.device_protocol` import

2024-04-09 10:06 UTC, marmarek commented on qubesguidaemon/mic.py
> +class MicDevice(qubes.device_protocol.DeviceInfo):
Actually, it should be `qubes.devices.DeviceInfo`... `device_protocol` is in `qubesadmin`

2024-04-10 03:48 UTC, piotrbartman commented on qubesguidaemon/mic.py
> +class MicDevice(qubes.device_protocol.DeviceInfo):
You were right, I didn't update core-admin, but it should be OK now: [QubesOS/qubes-core-admin/pull/579/commits/1004c670b76019ff83d0d1587d2a23c514c2cd4b](https://github.com/QubesOS/qubes-core-admin/pull/579/commits/1004c670b76019ff83d0d1587d2a23c514c2cd4b)

2024-04-12 02:05 UTC, marmarek commented on qubesguidaemon/mic.py
> +            qubes.device_protocol.DeviceInterface("******", devclass="mic")]
The mic device needs some more info, to avoid confusing "unknown mic device" description:
https://openqa.qubes-os.org/tests/96797#step/qui_widgets_devices/4

2024-04-12 04:23 UTC, piotrbartman commented on qubesguidaemon/mic.py
> +            qubes.device_protocol.DeviceInterface("******", devclass="mic")]
I've changed it to "microphone (build-in)"

2024-06-15 19:30 UTC, marmarek approved these changes

2024-06-15 19:34 UTC, merged