audio: change "low latency" buffer parameters
QubesOS/qubes-gui-daemon pull request #140
Opened 2024-02-22 16:00 UTC by marmarek

Related to QubesOS/qubes-issues#8955

2024-02-22 16:02 UTC, marmarek commented
FYI @DemiMarie I've added logging I used for graphs here. Since it proved useful, I'll make it opt-in in default binary too.

2024-02-22 17:15 UTC, DemiMarie requested changes
I am quite concerned about a latency regression here.  I would prefer to set `.maxlength` to 4096, while keeping `.tlength` at 4096.

2024-02-22 17:15 UTC, DemiMarie commented on pulse/pacat-simple-vchan.c
> +    .tlength = (uint32_t)-1
Is this reasonable?  The documentation says:

```c
    /**< Playback only: target length of the buffer. The server tries                         
     * to assure that at least tlength bytes are always available in                          
     * the per-stream server-side playback buffer. The server will                            
     * only send requests for more data as long as the buffer has                             
     * less than this number of bytes of data.                                                
     *
     * It is recommended to set this to (uint32_t) -1, which will                             
     * initialize this to a value that is deemed sensible by the
     * server. However, this value will default to something like 2s;                         
     * for applications that have specific latency requirements                               
     * this value should be set to the maximum latency that the                               
     * application can deal with.                                                             
     *
     * When PA_STREAM_ADJUST_LATENCY is not set this value will                               
     * influence only the per-stream playback buffer size. When
     * PA_STREAM_ADJUST_LATENCY is set the overall latency of the sink                        
     * plus the playback buffer size is configured to this value. Set
     * PA_STREAM_ADJUST_LATENCY if you are interested in adjusting the                        
     * overall latency. Don't set it if you are interested in                                 
     * configuring the server-side per-stream playback buffer                                 
     * size. */                                                                               
```

2s is way, *way* too high.  I would much prefer to keep this at 4096.

2024-02-22 17:15 UTC, DemiMarie commented on pulse/pacat-simple-vchan.c
> +    .maxlength = 8192,
```suggestion
    .maxlength = 4096,
```

2024-02-22 17:40 UTC, marmarek commented on pulse/pacat-simple-vchan.c
> +    .tlength = (uint32_t)-1
It can't be higher than maxlength (which is buffer size).

2024-02-22 17:43 UTC, marmarek commented on pulse/pacat-simple-vchan.c
> +    .maxlength = 8192,
No. `PA_STREAM_ADJUST_LATENCY` is enabled, so this includes whatever buffer hardware has (which in fact may be even larger than 8k). Furthermore, PW agent sends data in 4096 chunks, so having maxlength 4k means missing just one write will lead to underrun.

2024-02-22 17:47 UTC, marmarek commented
> I am quite concerned about a latency regression here

It isn't regression at all. maxlength used to be server default, which IIUC is about 4MB. PA agent used smaller vchan buffer, so it didn't manage to fill the whole PA's buffer, but it was exactly 8k buffer.

2024-02-22 17:49 UTC, marmarek commented
And generally (_if_ that would be the case, which isn't) no underruns takes priority over low latency.

2024-02-22 19:16 UTC, DemiMarie requested changes
Buffer attribute changes look fine, but if `pa_stream_get_latency()` fails the code will log either wrong data or uninitialized stack rubble.

2024-02-22 19:16 UTC, DemiMarie commented on pulse/pacat-simple-vchan.c
> +        pacat_log("process_playback_data(): vchan data %d max_length %d latency %llu", space_in_vchan, max_length, latency);
```suggestion
        if (pa_stream_get_latency(s, &latency, &negative))
            pacat_log("pa_stream_get_latency() failed");
        else
            pacat_log("process_playback_data(): vchan data %d max_length %d latency %llu", space_in_vchan, max_length, latency);
```

otherwise we might log uninitialized stack rubble

2024-02-22 20:38 UTC, marmarek commented on pulse/pacat-simple-vchan.c
> +        pacat_log("process_playback_data(): vchan data %d max_length %d latency %llu", space_in_vchan, max_length, latency);
Yes, but a) I still want other values logged, and b) thanks to `PA_STREAM_INTERPOLATE_TIMING` that happens basically only once at the very start.

2024-02-22 22:29 UTC, DemiMarie commented on pulse/pacat-simple-vchan.c
> +        int negative;
```suggestion
        int negative = 0;
```

avoid logging junk from the stack

2024-02-23 00:08 UTC, marmarek commented on pulse/pacat-simple-vchan.c
> +        int negative;
I don't use the value at all, so it doesn't matter.

2024-02-23 10:55 UTC, marmarek commented
> system_tests_basic_vm_qrexec_gui@hw1
> 
>     * TC_20_AudioVM_Pulse_debian-12-xfce: [test_223_audio_play_hvm](https://openqa.qubes-os.org/tests/92414#step/TC_20_AudioVM_Pulse_debian-12-xfce/4) (failure)
>       `AssertionError: frequency 977.2385421984841 not in specified range,...`
> 
>     * TC_20_AudioVM_Pulse_fedora-38-xfce: [test_223_audio_play_hvm](https://openqa.qubes-os.org/tests/92414#step/TC_20_AudioVM_Pulse_fedora-38-xfce/4) (failure)
>       `AssertionError: frequency 986.4409885532086 not in specified range,...`
> 
>     * TC_20_AudioVM_Pulse_whonix-workstation-17: [test_220_audio_play_pulseaudio](https://openqa.qubes-os.org/tests/92414#step/TC_20_AudioVM_Pulse_whonix-workstation-17/1) (failure)
>       `AssertionError: frequency 945.4942192569575 not in specified range,...`
> 
>     * TC_20_AudioVM_Pulse_whonix-workstation-17: [test_223_audio_play_hvm](https://openqa.qubes-os.org/tests/92414#step/TC_20_AudioVM_Pulse_whonix-workstation-17/4) (failure)
>       `AssertionError: too short audio, expected 10s, got 8.94485260770975...`

This is a regression. Those tests are about emulated sound card for HVM, so PipeWire agent is not involved. But PulseAudio agent running in a stubdomain is. Depending on a test, both playback and recording failed. I'll inspect logs more closely and experiment with some parameters, but I suspect changing maxlength for the recording stream is a mistake. But it could be also related to migration to PipeWire in dom0, not this PR.

2024-02-23 17:54 UTC, marmarek commented
The HVM playback was problem in a test (yet another difference between Pulseaudio and PipeWire). But HVM recording seems to be legit issue.

2024-02-23 20:39 UTC, DemiMarie commented
Want me to make the changes conditional on buffer sizes?  The PipeWire agent uses much bigger buffers.

2024-02-23 20:56 UTC, marmarek commented
If that will be necessary, I can also add an option for that (qvm-start-daemon knows very well if given pacat process is for the domain itself or its stubdomain).

2024-02-23 21:48 UTC, marmarek commented
I have an alternative idea - instead of changing buffer parameters, change how much data is read from the vchan, using this:
```
/** Return the number of bytes requested by the server that have not yet
 * been written.
 *
 * It is possible to write more than this amount, up to the stream's
 * buffer_attr.maxlength bytes. This is usually not desirable, though, as
 * it would increase stream latency to be higher than requested
 * (buffer_attr.tlength).
 *
 * (size_t) -1 is returned on error.
 */
size_t pa_stream_writable_size(const pa_stream *p);
```

2024-02-23 22:31 UTC, DemiMarie commented
@marmarek The code already does this for reads initiated by vchan activity.

2024-02-23 22:48 UTC, marmarek commented
Hmm, I'm trying to get what is the size (nbytes) parameter to the write callback. In our code it's called `max_length`, but it isn't clear if it's really max size or requested size.

2024-02-23 23:21 UTC, marmarek commented
But in that case, my change tlength->maxlength shouldn't matter for playback. But as the failing recording test shows, it does matter for recording, in negative way. I'll rollback the change, but maybe make tlength configurable?

Oh, and also, fragsize 4096 is incompatible with PA's agent 2048 vchan size, and it works only due to blocking vchan calls. I'll try changing to 2048 and see if that helps.

2024-02-23 23:22 UTC, marmarek commented
or better change PA's agent vchan to 4096 ?

2024-02-23 23:32 UTC, marmarek commented
In any case, this shows rather clearly that prebuf/tlength handling is broken in Pulseaudio...

2024-02-24 14:30 UTC, marmarek commented
> The HVM playback was problem in a test (yet another difference between Pulseaudio and PipeWire). But HVM recording seems to be legit issue.

Or maybe another issue with tests? I found this in the log:
```
1708756176.132966 Buffer metrics: maxlength=4194304, tlength=4096, prebuf=4294967295, minreq=4294967295
1708756176.133012 Using sample spec 's16le 2ch 44100Hz', channel map 'front-left,front-right'.
1708756176.150634 Connected to device alsa_output.pci-0000_00_03.0.analog-stereo.monitor (48, not suspended).
1708756176.150793 Recording requested but not allowed
1708756176.180393 Stream started.[K
1708756176.184494 Stream underrun.[K
1708756176.210018 Stream started.[K
1708756177.311861 Stream underrun.[K
1708756177.320785 Stream started.[K
1708756179.361800 Stream underrun.[K
1708756179.362170 Stream started.[K
1708756179.525348 Stream underrun.[K
1708756179.548189 Stream started.[K
1708756180.041450 Stream underrun.[K
1708756180.059797 Stream started.[K
1708756184.109916 Stream underrun.[K
1708756184.129262 Stream started.[K
2024-02-24 01:29:45,889 icon-receiver: connected: test-inst-vm1
1708756186.376039 Setting audio-input to enabled
1708756186.376245 Recording start
app: Connection to qubesd terminated, reconnecting in 1.0 seconds
```

So, recording was enabled quite late in the test, no wonder it recorded shorter sound than intended (or nothing at all). But also, there was a few underruns, might be relevant.
Anyway, this needs a closer look, the issue wasn't there before migrating to PipeWire.

2024-02-24 18:01 UTC, marmarek commented
The HVM recording on debian-12 seems to be a pipewire bug (see https://github.com/QubesOS/qubes-issues/issues/8590). It's fixed in newer pipewire (and so the test passes on fedora template). It was "working" before because the test was broken (and I got it fixed in https://github.com/QubesOS/qubes-core-admin/pull/581). I'll exclude it for now.

Remaining thing to check is recording on whonix-workstation template - which runs pulseaudio (not pipewire-pulse).

2024-02-25 03:48 UTC, marmarek commented
> Remaining thing to check is recording on whonix-workstation template - which runs pulseaudio (not pipewire-pulse).

I'm struggling with this case. It looks like with pipewire in dom0 it fails, but with pulseaudio in dom0 it works. More specifically, the failing setup is:
- qube based on whonix-workstation-17
- pulseaudio inside the qube (as whonix-ws has), with qubes module unloaded
- virt_mode hvm
- qvm-features audio-model ich6
- running on nested virt (inside KVM)
- dom0 configured to record "monitor" stream by default, and recording allowed for the test qube
- playing in dom0, and recording in VM

I've tried changing various parameters, like fragsize (both down and up), and also updated PA agent inside stubdomain (so it uses 8KiB vchan buffer instead of 2KiB). Nothing helped. What does help is switching dom0 audio daemon back to pulseaudio. The test passes also with (new, fedora-38) pipewire running inside the qube. 

The result is some missing samples, mostly in the middle. And the test fails with: ` AssertionError: too short audio, expected 10s, got 8.36628117913832...` Recorded audio can be fetched from https://openqa.qubes-os.org/tests/92456/file/system_tests-audio-sample-qubes.tests.integ.vm_qrexec_gui.tar.gz (play with `paplay --raw --format=float32le --rate=44100 --channels=1`).

The specific setup above is unusual enough (especially the nested virt) that it shouldn't matter in theory. But very obvious issues in this setup usually correlated with more subtle issues on more usual configurations. And it's usually easier to debug more obvious issue. What I worry here, is that switching audio daemon in dom0 will regress audio recording for non-Linux HVMs (or even Linux, but without qubes packages).

Any ideas what else I can try?

2024-02-25 04:57 UTC, DemiMarie commented
> > Remaining thing to check is recording on whonix-workstation template - which runs pulseaudio (not pipewire-pulse).
> 
> I'm struggling with this case. It looks like with pipewire in dom0 it fails, but with pulseaudio in dom0 it works. More specifically, the failing setup is:
> 
> * qube based on whonix-workstation-17
> * pulseaudio inside the qube (as whonix-ws has), with qubes module unloaded
> * virt_mode hvm
> * qvm-features audio-model ich6
> * running on nested virt (inside KVM)
> * dom0 configured to record "monitor" stream by default, and recording allowed for the test qube
> * playing in dom0, and recording in VM
> 
> I've tried changing various parameters, like fragsize (both down and up), and also updated PA agent inside stubdomain (so it uses 8KiB vchan buffer instead of 2KiB). Nothing helped. What does help is switching dom0 audio daemon back to pulseaudio. The test passes also with (new, fedora-38) pipewire running inside the qube.
> 
> The result is some missing samples, mostly in the middle. And the test fails with: ` AssertionError: too short audio, expected 10s, got 8.36628117913832...` Recorded audio can be fetched from https://openqa.qubes-os.org/tests/92456/file/system_tests-audio-sample-qubes.tests.integ.vm_qrexec_gui.tar.gz (play with `paplay --raw --format=float32le --rate=44100 --channels=1`).
> 
> The specific setup above is unusual enough (especially the nested virt) that it shouldn't matter in theory. But very obvious issues in this setup usually correlated with more subtle issues on more usual configurations. And it's usually easier to debug more obvious issue. What I worry here, is that switching audio daemon in dom0 will regress audio recording for non-Linux HVMs (or even Linux, but without qubes packages).
> 
> Any ideas what else I can try?

1. @adrelanos is switching to PipeWire an option?
2. What about using PipeWire in the stubdomain, or (better yet) having QEMU talk to pacat directly, with no audio server involved?

2024-02-25 10:47 UTC, marmarek commented
> 1. is switching to PipeWire an option?

That is not the point... I fear what we see here is a symptom of broken audio in HVM in general, that will manifest in other cases, maybe even not Linux.

> 2\. What about using PipeWire in the stubdomain, or (better yet) having QEMU talk to pacat directly, with no audio server involved?

The former I don't like, due to significantly higher memory usage for PipeWire, which is even more critical in stubdomain. The latter might be an option in theory, but given how "well" it went with pipewire agent implementation, I'm skeptical we will improve the situation this way.

2024-02-25 11:00 UTC, marmarek commented
Oh, and if I retry the test few more times, it fails with new pipewire in the VM too. But after switching to pulseaudio in dom0 it works every time.

2024-02-25 12:44 UTC, adrelanos commented
> 1. @adrelanos is switching to PipeWire an option?

As far as Qubes-Whonix is concerned, yes, very much so. This is unspecific to Qubes-Whonix.

(Non-Qubes-Whonix is already on PipeWire.)

[qubes-whonix `debian/control`](https://github.com/Whonix/qubes-whonix/blob/master/debian/control) contains `Depends:` on  `pulseaudio-qubes`. Happy to change to something else. Please let me know.

2024-02-25 20:46 UTC, DemiMarie commented
> Oh, and if I retry the test few more times, it fails with new pipewire in the VM too. But after switching to pulseaudio in dom0 it works every time.

So I think the test matrix is:

1. direction: recording vs playback
2. dom0 audio server: PipeWire + pipewire-pulse vs PulseAudio
3. system: nested virt vs bare hardware
4. guest audio: emulated vs Qubes PV
5. guest audio server: PulseAudio vs PipeWire

Which of these 32 possibilities are good and which are bad?  Is there an openQA run where I can look at the results of all of these?

My understanding is:

1. With PipeWire in both dom0 and domU, QubesOS/qubes-gui-agent-linux#207 is needed to fix a single underrun immediately after the stream is uncorked.  Otherwise, everything works fine on bare hardware, but I have no idea about nested virt.
2. With PulseAudio in dom0, a PulseAudio server bug causes very large latency and problems with the PipeWire agent.  This problem is independent of PipeWire vs PulseAudio in the guest, but the PulseAudio agent doesn’t trigger it, presumably because of extra buffering there.
3. Earlier revisions in this PR tried and failed work around the PulseAudio bug, so the plan is to switch to PipeWire in dom0.
4. Switching to PipeWire in dom0 fixes playback in all cases, but _recording_ is now broken in a subset of cases.

Is this accurate?  I’m somewhat confused as to what is happening here, which is why I am asking for the results in all 32 possible cases.

2024-02-26 02:13 UTC, marmarek commented
> Which of these 32 possibilities are good and which are bad? Is there an openQA run where I can look at the results of all of these?

I think it should be possible to collect all the combinations.

Take a most recent run: https://openqa.qubes-os.org/tests/overview?distri=qubesos&version=4.2&build=2024022504-4.2&flavor=pull-requests

click on vm_qrexec_gui tests

> direction: recording vs playback

"rec" or "play" in test name

> dom0 audio server: PipeWire + pipewire-pulse vs PulseAudio

recent runs use pipewire in dom0; for pulseaudio in dom0 you need an earlier run, for example this: https://openqa.qubes-os.org/tests/overview?distri=qubesos&version=4.2&build=2024021900-4.2&groupid=11; but note the audio_rec_unmuted_hvm test wasn't fixed at that time, so it's skipped in many cases)

> system: nested virt vs bare hardware

the one with "@hw1" is on bare hardware, others are nested virt

> guest audio: emulated vs Qubes PV

"hvm" in test name is emulated, others are qubes pv

> guest audio server: PulseAudio vs PipeWire

template:
 - fedora - pipewire >= 1.0
 - debian - pipewire 0.3.something
 - whonix-workstation - pulseaudio
 - whonix-gateway - nothing (and test skipped)

Especially for nested virt, check few jobs (the whole vm_qrexec_gui suite is ran several times with different storage, so you have quite a few data points) - a single passing instance doesn't necessarily mean it's good. Failures are collected in qubesos-bot message in relevant PR (this included), you can check edits history for older reports - that's usually quicker way than manually clicking on all the jobs.

Oh, and one more thing, failure "only silence detected" is not interesting - it's either buggy test, or the known issue in the old pipewire.



> My understanding is:
> 
>     1. With PipeWire in both dom0 and domU, https://github.com/QubesOS/qubes-gui-agent-linux/pull/207 is needed to fix a single underrun immediately after the stream is uncorked. Otherwise, everything works fine on bare hardware, but I have no idea about nested virt.

For PV audio - yes, both bare hw and nested virt is good. And the _single_ underrun at the start is not a problem (looks like an artifact prebuf kicking in), so that PR isn't needed IMO.

> 2\. With PulseAudio in dom0, a PulseAudio server bug causes very large latency and problems with the PipeWire agent.  This problem is independent of PipeWire vs PulseAudio in the guest, but the PulseAudio agent doesn’t trigger it, presumably because of extra buffering there.

Large latencies _and_ a lot of underruns for several seconds after starting playback on nested virt (and some less on bare hw, but still problematic). Neither of those problem affect dom0 PA + domU PA setup, only dom0 PA + domU PW is affected.

> 3\. Earlier revisions in this PR tried and failed work around the PulseAudio bug, so the plan is to switch to PipeWire in dom0.

Yes.

> 4\. Switching to PipeWire in dom0 fixes playback in all cases, but _recording_ is now broken in a subset of cases.

Recording using emulated audio is affected. And on the very last run, I see a single failure of emulated playback (with pulseaudio in domU).

2024-02-27 02:25 UTC, DemiMarie commented
> > 1. With PipeWire in both dom0 and domU, https://github.com/QubesOS/qubes-gui-agent-linux/pull/207 is needed to fix a single underrun immediately after the stream is uncorked. Otherwise, everything works fine on bare hardware, but I have no idea about nested virt.
> 
> For PV audio - yes, both bare hw and nested virt is good. And the _single_ underrun at the start is not a problem (looks like an artifact prebuf kicking in), so that PR isn't needed IMO.

I’d still like to eliminate the underrun, mostly because it can hide _real_ underruns (not due to prebuf) which indicate actual problems.  I vaguely remember this being a problem when developing the PipeWire agent.

2024-02-27 03:22 UTC, marmarek commented
What I don't like about that PR is second-guessing what dom0 part is doing, including some variable parameters (like buffer size to fill in). That will lead to issues sooner or latter (for example, if we'd reduce pacat buffer sizes at some point in the future, the prefill PR will cause overruns at start). If pacat needs to delay uncork until at least some amount of data is collected, it's the job of pacat to do that, not domU agent. And the prebuf feature does exactly that. I'm not sure why I haven't managed to get it working with real Pulseaudio (it could be a bug in PA, but very well it could be also some other bug in pacat), but with PipeWire in dom0 it seems to work correctly.

2024-04-05 17:06 UTC, merged