pacat-simple-vchan: reconnect on vchan eof
QubesOS/qubes-gui-daemon pull request #141
Opened 2024-03-26 10:04 UTC by fepitre

https://github.com/QubesOS/qubes-issues/issues/8975

2024-04-13 14:38 UTC, marmarek requested changes

2024-04-13 14:38 UTC, marmarek commented on pulse/pacat-simple-vchan.c
> +        goto main;
This should be before removing the pidfile, otherwise you end up without it after reconnect.

2024-04-13 14:38 UTC, marmarek commented on pulse/pacat-simple-vchan.c
>          perror("libvchan_client_init_async");
This case is now not only initial connect (which, if fails, should result in non-zero exit code), but also in case of reconnect (which may be a clean domain shutdown). In the latter case, exit should be clean. Maybe use `exit(u.ret)` here, which should be 0 in the reconnect case? But also, going for exit directly here will leave pidfile not cleaned up... So, either clean it up here (and similarly in exit() calls below), or add a goto label to the pidfile cleanup at the end of main().

2024-04-23 10:02 UTC, fepitre commented on pulse/pacat-simple-vchan.c
>          perror("libvchan_client_init_async");
I've made a proposal by simply calling a function instead of adding another goto.

2024-04-24 15:46 UTC, marmarek requested changes

2024-04-24 15:46 UTC, marmarek commented on pulse/pacat-simple-vchan.c
> +    cleanup_pidfile(pidfile_path, pidfile_fd);
Here you remove the pidfile on reconnect. You have a call at the very end of the main function already, remove this one.

2024-04-28 01:18 UTC, marmarek approved these changes

2024-04-28 01:19 UTC, merged