Use QubesDB for knowing if mic is allowed or not
QubesOS/qubes-gui-daemon pull request #145
Opened 2024-07-05 14:18 UTC by fepitre

2024-07-08 18:49 UTC, marmarek requested changes

2024-07-08 18:49 UTC, marmarek commented on qubesguidaemon/mic.py
> +    async def on_property_set(
property set handler can't be async.

2024-07-09 01:15 UTC, marmarek commented on qubesguidaemon/mic.py
> +            mic_allowed = oldvalue.untrusted_qdb.read(
And another thing found by tests - you can't access qdb when VM is not running (untrusted_qdb is None then).

2024-07-09 01:17 UTC, marmarek commented on qubesguidaemon/mic.py
> +            mic_allowed = oldvalue.untrusted_qdb.read(
There are three cases:
- "subject" VM is not running - do nothing then
- old audiovm is not running - do nothing (as if mic was not attached)
- new audiovm is not running - here I'm not sure, especially if mic was attached; at least log a warning

2024-07-09 01:26 UTC, marmarek commented on qubesguidaemon/mic.py
> +            if mic_allowed not in (b"0", b"1"):
This can be also missing (`None`? needs checking), when relevant pacat process is not running (or is an older version)

2024-07-09 23:21 UTC, marmarek commented
> * TC_20_AudioVM_Pulse_debian-12-xfce: [test_252_audio_playback_audiovm_switch_hvm](https://openqa.qubes-os.org/tests/105938#step/TC_20_AudioVM_Pulse_debian-12-xfce/7) (error)
>       `qubes.exc.QubesVMError: Invalid value for /audio-input/test-inst-vm...`

Unfortunately error message doesn't tell what value was there actually...

> * TC_20_AudioVM_Pulse_fedora-40-xfce: [test_222_audio_rec_unmuted_pulseaudio](https://openqa.qubes-os.org/tests/105939#step/TC_20_AudioVM_Pulse_fedora-40-xfce/3) (error)
>       `qubes.devices.DeviceAlreadyAttached: 'device dom0:mic of class mic ...`

First test passed and only later one failed. I think it's about stale entry from previous VM startup. Remove it in `domain-qdb-create` event handler (it's part of domain startup).

2024-07-09 23:22 UTC, marmarek commented
> * TC_20_AudioVM_PipeWire_fedora-40-xfce: [test_250_audio_playback_audiovm_pipewire](https://openqa.qubes-os.org/tests/105938#step/TC_20_AudioVM_PipeWire_fedora-40-xfce/4) (error)
>       `AttributeError: 'NoneType' object has no attribute 'is_running'`

And also this issue

2024-07-09 23:27 UTC, marmarek commented
> * TC_20_AudioVM_PipeWire_fedora-40-xfce: [test_260_audio_mic_enabled_switch_audiovm](https://openqa.qubes-os.org/tests/105938#step/TC_20_AudioVM_PipeWire_fedora-40-xfce/6) (failure)
>       `AssertionError: source-output for VM test-inst-vm1 not found`

This is the actual test. My guess is `_configure_audio_recording` doesn't handle recording with audiovm, it looks to call pactl only in dom0. `common_audio_record_unmuted` looks to also support only recording with dom0 as audiovm... It might be enough to prepend `qvm-run -p ...` to those commands in case of audiovm.

2024-07-10 07:38 UTC, fepitre commented
> > * TC_20_AudioVM_Pulse_debian-12-xfce: [test_252_audio_playback_audiovm_switch_hvm](https://openqa.qubes-os.org/tests/105938#step/TC_20_AudioVM_Pulse_debian-12-xfce/7) (error)
> >   `qubes.exc.QubesVMError: Invalid value for /audio-input/test-inst-vm...`
> 
> Unfortunately error message doesn't tell what value was there actually...

Yes, I thought it would be a bad idea to display it, I will adapt it.

2024-07-17 10:12 UTC, marmarek commented on qubesguidaemon/mic.py
> +                mic_allowed.decode("utf-8")
since you care about `"0"` and `"1"` only, better use `ascii`; and in any case, handle UnicodeDecodeError

2024-07-17 10:20 UTC, marmarek commented on qubesguidaemon/mic.py
> +                mic_allowed.decode("utf-8")
or simply compare against `b"0"` and `b"1"`

2024-07-20 16:52 UTC, marmarek requested changes

2024-07-20 16:52 UTC, marmarek commented on pulse/pacat-simple-vchan.c
> +        free(u->qdb_config_path);
free other paths too?

and since we have a separate config and status paths, maybe restore removing status path (to signal it isn't really connected anymore)?

2024-07-20 16:52 UTC, marmarek commented on pulse/pacat-simple-vchan.c
> +    u->qdb_config_path = NULL;
free other paths on failure too

2024-07-21 17:27 UTC, marmarek commented
https://openqa.qubes-os.org/tests/107154#step/update_guivm/22
```
Jul 21 13:05:34 dom0 qubesd[1412]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.Start' dest=b'sys-gui-vnc' arg=b'' len(untrusted_payload)=0
Jul 21 13:05:34 dom0 qubesd[1412]: Traceback (most recent call last):
Jul 21 13:05:34 dom0 qubesd[1412]:   File "/usr/lib/python3.11/site-packages/qubes/api/__init__.py", line 291, in respond
Jul 21 13:05:34 dom0 qubesd[1412]:     response = await self.mgmt.execute(
Jul 21 13:05:34 dom0 qubesd[1412]:                ^^^^^^^^^^^^^^^^^^^^^^^^
Jul 21 13:05:34 dom0 qubesd[1412]:   File "/usr/lib/python3.11/site-packages/qubes/api/admin.py", line 866, in vm_start
Jul 21 13:05:34 dom0 qubesd[1412]:     await self.dest.start()
Jul 21 13:05:34 dom0 qubesd[1412]:   File "/usr/lib/python3.11/site-packages/qubes/vm/qubesvm.py", line 1277, in start
Jul 21 13:05:34 dom0 qubesd[1412]:     self.create_qdb_entries()
Jul 21 13:05:34 dom0 qubesd[1412]:   File "/usr/lib/python3.11/site-packages/qubes/vm/qubesvm.py", line 2397, in create_qdb_entries
Jul 21 13:05:34 dom0 qubesd[1412]:     self.fire_event('domain-qdb-create')
Jul 21 13:05:34 dom0 qubesd[1412]:   File "/usr/lib/python3.11/site-packages/qubes/events.py", line 195, in fire_event
Jul 21 13:05:34 dom0 qubesd[1412]:     sync_effects, async_effects = self._fire_event(event, kwargs,
Jul 21 13:05:34 dom0 qubesd[1412]:                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 21 13:05:34 dom0 qubesd[1412]:   File "/usr/lib/python3.11/site-packages/qubes/events.py", line 164, in _fire_event
Jul 21 13:05:34 dom0 qubesd[1412]:     effect = func(self, event, **kwargs)
Jul 21 13:05:34 dom0 qubesd[1412]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 21 13:05:34 dom0 qubesd[1412]:   File "/usr/lib/python3.11/site-packages/qubesguidaemon/mic.py", line 226, in on_domain_qdb_create
Jul 21 13:05:34 dom0 qubesd[1412]:     vm.audiovm.untrusted_qdb.rm("/audio-input-config/{}".format(vm.name))
Jul 21 13:05:34 dom0 qubesd[1412]:     ^^^^^^^^^^^^^^^^^^^^^^^^
Jul 21 13:05:34 dom0 qubesd[1412]: AttributeError: 'NoneType' object has no attribute 'untrusted_qdb'
```

Since it accesses `vm.audiovm.untrusted_qdb`, it needs to check if it's running, similar to other places.

2024-08-08 02:18 UTC, marmarek approved these changes

2024-08-08 02:20 UTC, merged