Make maximum clipboard buffer lenght configurable
QubesOS/qubes-gui-daemon pull request #150
Opened 2024-10-06 09:58 UTC by alimirjamali

1st part of fix. Making the clipboard buffer size configurable via `max_clipboard_size` setting within `guid.conf`

fixes: https://github.com/QubesOS/qubes-issues/issues/9296

2024-10-06 10:48 UTC, marmarek requested changes

2024-10-06 10:48 UTC, marmarek commented on gui-daemon/xside.c
> +    if (untrusted_len > g->clipboard_buffer_size) {
This is not that simple. As you can see here, if VM provides too much data, it gets disconnected (`exit(1)` below). So, there either needs to be a mechanism to tell the max size to the VM, or a more graceful handling of too long data. For the latter it needs to be read from the client (read_data) in full, even if too long, otherwise remainder would be interpreted as subsequent commands. And be careful to not turn this into denial-of-service by allocating VM-controlled arbitrary large memory buffer below (when reading to discard, do it in chunks).

2024-10-06 11:59 UTC, alimirjamali commented on gui-daemon/xside.c
> +    if (untrusted_len > g->clipboard_buffer_size) {
Will work on it. If this is ever going to be user configurable, maybe it is better to keep it simple for the time and set `MAX_CLIPBOARD_BUFFER_SIZE` in PR to 250000 characters. This was even accepted before the [Big Requests Extension](https://www.x.org/releases/X11R7.7/doc/bigreqsproto/bigreq.html) and INCR in mid 90s. 

User's major concern is truncation without notification. It would better to spend more time on that.

Unrelated question. Is the Gitlab CI/CD infra still broken? All the Fedora & Debian builds have failed.

2024-10-06 13:26 UTC, marmarek commented on gui-daemon/xside.c
> +    if (untrusted_len > g->clipboard_buffer_size) {
> Unrelated question. Is the Gitlab CI/CD infra still broken? All the Fedora & Debian builds have failed.

It looks like viewing results without logging into gitlab.com is still broken. But the reason for the failures is that this PR really fails to build.

2024-10-06 13:48 UTC, marmarek commented on gui-daemon/xside.c
> +    if (untrusted_len > g->clipboard_buffer_size) {
Oh, and technically, when bumping maximum clipboard size, it needs also bumping protocol version, so the agent sees that it can send more data.

2024-10-06 14:23 UTC, alimirjamali commented on gui-daemon/xside.c
> +    if (untrusted_len > g->clipboard_buffer_size) {
> But the reason for the failures is that this PR really fails to build.

I tried to cheat a little since setting up the build environment on Fedora 41 is problematic (and it appears that CI/CD also lacks Fedora 41 builds). But no worries. It is finally the moment for me to learn builderv2 instead of quickly testing everything locally.

2024-10-06 18:47 UTC, alimirjamali commented on gui-daemon/xside.c
> +    if (untrusted_len > g->clipboard_buffer_size) {
My overall plan & design is going to be simple. Letting agent to send up to the new `MAX_CLIPBOARD_BUFFER_SIZE + 1` characters (250KB+1) in [this line](https://github.com/QubesOS/qubes-gui-agent-linux/blob/main/gui-agent/vmside.c#L990). Then `xside` should simply reject sizes over `g->clipboard_buffer_size` and clear the buffer [in this block](https://github.com/QubesOS/qubes-gui-daemon/blob/main/gui-daemon/xside.c#L1022-L1026); with proper notification to user about it.

The wasted 250KB for this simple mechanism is not that bad and is comparable to some 256x256 pixel PNGs. It is better than sending a truncated clipboard IMO. Hopefully this should require minimum modification to agent side and fully backward compatible (templates with old protocol will truncate the clipboard as before).

This will need more testing and changes to 3 repositories. I am currently doing my testings in Fedora 40.

2024-10-10 02:35 UTC, marmarek requested changes

2024-10-10 02:35 UTC, marmarek commented on gui-daemon/xside.c
> -        exit(1);
This needs more care. If VM gave some large number, you can't simply pass that to malloc below. That would allow VM to make gui-daemon allocate up to 4GB memory, most likely crashing it and starving few other processes too.
If limit is exceeded, you need to read and discard that data in chunks (that are not overly big). Or, apply some other upper limit (in the description you said it will be at most MAX_CLIPBOARD_SIZE+1, so maybe exit if that limit is exceeded too?).

2024-10-10 02:35 UTC, marmarek commented on gui-daemon/xside.c
> +    if (! clipboard_buffer_exceeded)    // do not write anything to output if size exceeds limit
I don't think empty file is a good idea for signaling that limit was exceeded. This may happen for other reasons too (for example when really VM clipboard was empty). Either adjust the message in https://github.com/QubesOS/qubes-desktop-linux-manager/pull/223 that too much data is just one of possible reasons, or have some other method to inform about too much data (yet another file?).

2024-10-10 02:35 UTC, marmarek commented on gui-daemon/xside.c
> +                    PROTOCOL_VERSION_MINOR);
This is not a program version, but protocol version.

2024-10-10 02:35 UTC, marmarek commented on gui-daemon/xside.c
> +    fprintf(stream, " --version\tshow program version\n");
```suggestion
    fprintf(stream, " --version\tshow protocol version\n");
```
?

2024-10-10 02:35 UTC, marmarek commented on gui-daemon/xside.h
> +#define DEFAULT_CLIPBOARD_BUFFER_SIZE 64000   // make this 1000 bytes less than previous value so it works with older vmside agent
How setting lower default limit makes it work with the old agent? It will reject sizes that were allowed before. If you want to detect (likely) truncation with the old agent, then maybe set it to 64999? It isn't 100% correct (if user really tries to copy exactly 65000 chars, it will be rejected now), but may be close enough. Or keep it at 65000 so the old agent is not affected at all.

2024-10-10 06:23 UTC, alimirjamali commented on gui-daemon/xside.c
> -        exit(1);
Yes. Right. It would be the case of a malicious VM that does not comply with the vmside patch. It is possible and should be handled. I will do it.

2024-10-10 06:29 UTC, alimirjamali commented on gui-daemon/xside.c
> +    if (! clipboard_buffer_exceeded)    // do not write anything to output if size exceeds limit
I also thought about it. Yet another file or maybe adding some metadata to `qubes-clipboard.bin.source`. The former option sounds more appealing. BTW, I think it would be better to keep it a structured file this time. So it could be used later for other purposes as well (such as adding some metadata).

2024-10-10 06:31 UTC, alimirjamali commented on gui-daemon/xside.c
> +                    PROTOCOL_VERSION_MINOR);
I thought it is good to have. Should I update it to print the protocol version or remove it entirely?

2024-10-10 06:31 UTC, alimirjamali commented on gui-daemon/xside.c
> +    fprintf(stream, " --version\tshow program version\n");
OK

2024-10-10 06:37 UTC, alimirjamali commented on gui-daemon/xside.h
> +#define DEFAULT_CLIPBOARD_BUFFER_SIZE 64000   // make this 1000 bytes less than previous value so it works with older vmside agent
This will work (if vmside protocol version is below 1.8). Anything above 64999 means either the vmside actual size was exactly 65000 characters (very low probability) or over it. Overall, rejecting sizes over 64999 characters (by default) is a good compromise if the user has a template with older vmside.

This default could be readjusted to 256000 after all templates with vmside versions of 1.7 or older are EOL.

I will adjust to 64999

2024-10-10 07:08 UTC, alimirjamali commented on gui-daemon/xside.h
> +#define DEFAULT_CLIPBOARD_BUFFER_SIZE 64000   // make this 1000 bytes less than previous value so it works with older vmside agent
I hope this could be reconsidered. I made the new default 64000 characters since it is kinda confusing to explain to users that the new default is 1 characters less than the previous default (64999). So the xside protocol version 1.8 could detect clipboard buffer exceeding on the vmsides protocol version less than 1.8.

Please advise.

2024-10-10 11:12 UTC, marmarek commented on gui-daemon/xside.h
> +#define DEFAULT_CLIPBOARD_BUFFER_SIZE 64000   // make this 1000 bytes less than previous value so it works with older vmside agent
Maybe make default 65000, but on the old protocol lower it to 64999 ? The limit can't be above 65000 on the old protocol anyway.

2024-10-10 14:47 UTC, alimirjamali commented on gui-daemon/xside.c
> +    if (! clipboard_buffer_exceeded)    // do not write anything to output if size exceeds limit
I am working on `save-clipboard-metadata` function. Technically the output `.metadata` file could be used to phase-out `.source` and `.xevent` files in future Qubes OS releases. I will make it a new commit for this PR instead of amending it. So it would be easier to follow-up and review.

2024-10-14 09:43 UTC, marmarek commented on gui-daemon/xside.c
> +
It should not only write the file, but also read it and use in relevant places, if not older than the data file.

2024-10-14 20:28 UTC, alimirjamali commented on gui-daemon/xside.c
> +
> It should not only write the file, but also read it and use in relevant places, if not older than the data file.

My original intention was to use it only for Global Clipboard systray widget. But this `.metadata` file could technically replace the old .source and .xevent files entirely. Beside the gui-daemon and systray widget, should I look elsewhere to fix? Is there anything else using the .source and .xevent files?

2024-10-14 20:36 UTC, alimirjamali commented on gui-daemon/xside.c
> -        exit(1);
This one is done with more care. It will `exit(1)` if vm sends over `MAX_CLIPBOARD_SIZE` (i.e. 65000) on Protocol v1.7 and over `MAX_CLIPBOARD_BUFFER_SIZE + 1` (i.e. 320001) on protocol 1.8 or newer.

I will add INCR detection here to reject INCR entirely.

2024-10-14 21:50 UTC, marmarek commented on gui-daemon/xside.c
> +
> My original intention was to use it only for Global Clipboard systray widget.

Intentional duplication of info (not only in transitional period) is not a good idea. The comment above suggests you already planned migration.

> Beside the gui-daemon and systray widget, should I look elsewhere to fix? Is there anything else using the .source and .xevent files?

There are also buttons "copy to global clipboard" in a bunch of places:
- qube logs in qube manager
- "this device" tab in qubes global config
- updater gui

2024-10-19 19:31 UTC, alimirjamali commented on gui-daemon/xside.c
> +
> > My original intention was to use it only for Global Clipboard systray widget.
> 
> Intentional duplication of info (not only in transitional period) is not a good idea. The comment above suggests you already planned migration.
> 
> > Beside the gui-daemon and systray widget, should I look elsewhere to fix? Is there anything else using the .source and .xevent files?
> 
> There are also buttons "copy to global clipboard" in a bunch of places:
> 
>     * qube logs in qube manager
>     * "this device" tab in qubes global config
>     * updater gui


This is almost ready for review. I am performing more local tests to assure it is working well. I decided to switch to JSON for `.metadata`. And completely phased-out `.source` and `.xevent` within the `qubes-guid` source. I have to work on the GTK and Qt tools next if this one is OK. I think the Qt and GTK tools should handle both the previous format and the new one for a while (if this is approved).

2024-10-19 22:57 UTC, marmarek commented on gui-daemon/xside.c
> +
Old files at least needs to be still created, for applications (possibly even 3rd-party ones) that still use those to get info about the clipboard.

2024-10-20 18:01 UTC, alimirjamali commented on gui-daemon/xside.c
> +
I restored creation of `.source` and `.xevent` files. I will work on the clipboard widget next.

The CI/CD build of this and `gui-agent` fail since they depends on the pending changes to headers of `gui-common`. My local build of qubes-guid takes almost 5 minutes. I guess if Demi's work to transition GUIVM to Wayland is going to take a long of time, it might be good idea to consider breaking `xside.c` to smaller parts (currently over 4700 lines).  For example clipboard functions in one file, keyboard processing in one file, ...

2024-10-21 15:30 UTC, alimirjamali commented on gui-daemon/xside.c
> +
This is now ready for review @marmarek 

I converted all 5 connected PRs from draft to ready.

2024-10-21 17:05 UTC, alimirjamali commented
PipelineRetryFailed

2024-10-22 23:45 UTC, marmarek commented
PipelineRetryFailed

2024-10-23 01:02 UTC, marmarek commented
PipelineRetry

2024-10-23 10:58 UTC, marmarek commented
Pasting doesn't work:
```
Failed to parse metadata line: {
```
But that's probably because copying failed:
```
Can not open /var/run/qubes/qubes-clipboard.bin.metadata file: No such file or directory
```

2024-10-23 10:59 UTC, marmarek commented
Ok, the message on copy is not really a failure - the first one is expected to not have this file. Can you suppress the error message in this case?

2024-10-23 11:04 UTC, marmarek commented on gui-daemon/xside.c
> +        if (! sscanf(line, "\"%[A-Za-z0-9]\":%[\"A-Za-z0-9]s,", key, value)) {
Shouldn't this check for `== 2` ?

2024-10-23 11:05 UTC, marmarek commented on gui-daemon/xside.c
> +        if (! sscanf(line, "\"%[A-Za-z0-9]\":%[\"A-Za-z0-9]s,", key, value)) {
and similarly all below should check sscanf result

2024-10-23 13:51 UTC, alimirjamali commented
> The metadata format needs to be documented somewhere. It has many more values than the old one, but also the parser is quite limited and can't understand full JSON - the limitations need to be described somewhere (expected line breaks, one value per line etc)

Exactly. I thought about it as well. Most use cases would be reading the metadata rather than writing to it. I wanted to avoid dependency on any external JSON parsing library for C language to support full JSON. In the end, all of xside.c should be replaced by Demi's rewrite of GUI daemons in Rust?

There is a mention of clipboard files in [qubes-doc](https://github.com/QubesOS/qubes-doc/blob/main/user/how-to-guides/how-to-copy-from-dom0.md?plain=1#L46-L48). But they are for end-user. I still believe that it might be a good place to document the metadata format.

2024-10-23 14:13 UTC, alimirjamali commented
> Ok, the message on copy is not really a failure - the first one is expected to not have this file. Can you suppress the error message in this case?

Yes. I guess instead of an error message, `metadata.successful = false` is better. `load_clipboard_metadata` is used only for `xevent_timestamp`. And it would be 0 which is already working.

2024-10-23 14:40 UTC, alimirjamali commented on gui-daemon/xside.c
> +        if (! sscanf(line, "\"%[A-Za-z0-9]\":%[\"A-Za-z0-9]s,", key, value)) {
> Shouldn't this check for `== 2` ?

Yes

> and similarly all below should check sscanf result

Most of them could be done in one sscanf. Most of them are `%d`. I will do it.

2024-10-23 14:44 UTC, marmarek commented
> Yes. I guess instead of an error message, `metadata.successful = false` is better.

TBH, I'm not a fan of mixing content of the loaded file with info about loading process itself. And also, the missing file needs special treatment anyway (compared to other errors on opening the file like permission denied) - missing file is okay on copy, and also kinda expected on some paste (if user didn't copied anything before). But for example permission error or io error are not okay (they should not be treated same as missing file). So, maybe in case of missing file report it via a return value from the function (making it more than a bool) and log message about it only in the paste path? But for other errors log errors directly from the loading function. Or, add a parameter whether missing file message should be logged?

2024-10-23 14:49 UTC, marmarek commented
> In the end, all of xside.c should be replaced by Demi's rewrite of GUI daemons in Rust?

One day maybe, but not anytime soon.

Anyway, it's okay to support just subset of JSON (as you said - it's mostly xside who write the file, but there are few where others write it too - for example copying dom0 clipboard via the clipboard widget). But it needs to be documented what that subset is.
You are correct that the current "format" is not documented, I think this would fit into https://www.qubes-os.org/doc/gui/ as other internals of qubes-guid are documented there.

2024-10-23 15:26 UTC, alimirjamali commented
> Pasting doesn't work:
> 
> ```
> Failed to parse metadata line: {
> ```

I just realized that sscanf includes `\n` at the end of string.

2024-10-23 16:35 UTC, alimirjamali commented
> > Yes. I guess instead of an error message, `metadata.successful = false` is better.
> 
> TBH, I'm not a fan of mixing content of the loaded file with info about loading process itself. And also, the missing file needs special treatment anyway (compared to other errors on opening the file like permission denied) - missing file is okay on copy, and also kinda expected on some paste (if user didn't copied anything before). But for example permission error or io error are not okay (they should not be treated same as missing file). So, maybe in case of missing file report it via a return value from the function (making it more than a bool) and log message about it only in the paste path? But for other errors log errors directly from the loading function. Or, add a parameter whether missing file message should be logged?

The [previous code](https://github.com/QubesOS/qubes-gui-daemon/blob/main/gui-daemon/xside.c#L794-L810) reported non-existent `.xevent` file. The new `get_clipboard_xevent_timestamp` function replaces the old `get_clipboard_file_xevent_timestamp` function. I tried to mimic the old behaviour on errors as much as possible.

I am doing some improvements and will send push them soon.

2024-10-23 19:42 UTC, alimirjamali commented
Found the error. In key, value parsing formatting string, I did not include underline as a valid character for key.

2024-10-23 21:04 UTC, alimirjamali commented
I am adding a special case if user tries to press ctrl+shift+c in a qube where the clipboard is empty. This can be handled with the new metadata (successful=true, cleared=true, sent_size=0)

2024-10-23 22:23 UTC, alimirjamali commented
I made another small adjustment. If `--max-clipboard-size=` command line value is not between 256 & 256000, the qubes-guid should revert to the default. Instead of exiting. Making this more forgiving to users

2024-10-24 01:06 UTC, marmarek commented on gui-daemon/xside.c
> +        if (sscanf(line, "\"%[A-Za-z0-9_-]\":%[\"A-Za-z0-9_-]s", key, value) != 2) {
```suggestion
        if (sscanf(line, "\"%[A-Za-z0-9_-]\":%[\"A-Za-z0-9_-]", key, value) != 2) {
```
?

2024-10-24 01:06 UTC, marmarek commented on gui-daemon/xside.c
> +        if (logging)
Errors other than ENOENT should result in a logged message even on copy operation.

2024-10-24 02:11 UTC, marmarek requested changes

2024-10-24 02:11 UTC, marmarek commented on gui-daemon/xside.h
> +};
As for documenting the metadata file, some extra explanation is needed for meaning of the fields at different stages (clipboard empty, something copied, something pasted) - especially it's not really obvious that after paste the "vmname" field changes its value.

2024-10-24 08:15 UTC, alimirjamali commented on gui-daemon/xside.h
> +};
I updated the explanation and added a link to `https://www.qubes-os.org/doc/gui/` for further information.

2024-10-24 08:28 UTC, alimirjamali commented on gui-daemon/xside.c
> +    fprintf(stream, " --max-clipboard-size=SIZE\tmaximum clipboard size VM is allowed to send to global clipboard\n");
Since it was working with `qvm-start-daemon` synthesized config file, I forgot about the command line. I will add it.

2024-10-24 09:27 UTC, alimirjamali commented on gui-daemon/xside.c
> +        if (logging)
> Errors other than ENOENT should result in a logged message even on copy operation. Similar comment applies to other messages below messages below. Generally, expected situation should not be reported as an error but others should get logged, and expected case is either fie exists and is correctly parsed, or file doesn't exist yet on the first copy.

I am having problem to properly understand this.
When you advise: `Errors other than ENOENT should result in a logged message even on copy operation`, 
does it mean always log or only if debug mode or verbose mode is enabled?

2024-10-24 09:40 UTC, alimirjamali commented on gui-daemon/xside.c
> +        if (logging)
@marmarek I applied all the other requested changes. For the error handling & messaging, there are 5 cases within `load_clipboard_metadata` and two cases within `get_clipboard_xevent_timestamp`. I have passed a boolean variable to those function (`g->log_level > 1`).  Maybe it is better to pass it as an integer and log based on different logging levels.

2024-10-24 13:05 UTC, marmarek commented
According to the tests the copy operation for 64000 and more fails (with default config and increased limit too). I haven't found any error messages in logs (the metadata has copy_action=1, successful=1, cleared=1).

2024-10-24 13:10 UTC, marmarek commented
Hmm, in some cases the 64k case works. But in none of the 4 iterations 200k worked.

2024-10-24 13:42 UTC, alimirjamali commented
> Hmm, in some cases the 64k case works. But in none of the 4 iterations 200k worked.

Was the fix I pushed to `gui-agent-linux` 13 hours ago applied to the tests? [This one](https://github.com/QubesOS/qubes-gui-agent-linux/pull/217/commits/79d44348ffd2c6fc5d7445c70509daf2468e75de).

2024-10-24 14:17 UTC, alimirjamali commented
Ok. In the updated unittest in [this line](https://github.com/QubesOS/qubes-core-admin/pull/623/files#diff-1c394520b6a434922c7a3e61e6d364ec44edd5f9a47372d2d60ad0583384ebabR585), it sets `gui-max-clipboard-size` feature per vm or per guivm? If it is guivm, it should be `gui-default-max-clipboard-size`

2024-10-24 14:22 UTC, alimirjamali commented
In [test_002_clipboard_300k](https://github.com/QubesOS/qubes-core-admin/pull/623/files#diff-1c394520b6a434922c7a3e61e6d364ec44edd5f9a47372d2d60ad0583384ebabR590-R593), does it expect a truncated zero byte `qubes-clipboard.bin`? It should not. The `gui-agent` sends specific string in case of INCR. [This one](https://github.com/QubesOS/qubes-gui-agent-linux/pull/217/files#diff-d2f30726ab5b690e7ac5631b2a30278386f40ada334a45b41787c59535b59333R1063).

I did the above as a temporary solution to INCR. Designing a signal from vmside to xside for the INCR is possible.

2024-10-24 14:46 UTC, alimirjamali commented
For `test_002_clipboard_200k_truncated`, it is failing on `AssertionError: '' != 'test-inst-vm1'`. It should not do this. In this case, the new code truncates the `/run/qubes/qubes-clipboard.bin` and sets `/run/qubes/qubes-clipboard.bin.source` to ""

2024-10-24 14:52 UTC, marmarek commented
> Ok. In the updated unittest in [this line](https://github.com/QubesOS/qubes-core-admin/pull/623/files#diff-1c394520b6a434922c7a3e61e6d364ec44edd5f9a47372d2d60ad0583384ebabR585), it sets `gui-max-clipboard-size` feature per vm or per guivm? If it is guivm, it should be `gui-default-max-clipboard-size`

It intends to set the per-vm one (for the source VM specifically).



> In [test_002_clipboard_300k](https://github.com/QubesOS/qubes-core-admin/pull/623/files#diff-1c394520b6a434922c7a3e61e6d364ec44edd5f9a47372d2d60ad0583384ebabR590-R593), does it expect a truncated zero byte `qubes-clipboard.bin`? It should not. The `gui-agent` sends specific string in case of INCR. [This one](https://github.com/QubesOS/qubes-gui-agent-linux/pull/217/files#diff-d2f30726ab5b690e7ac5631b2a30278386f40ada334a45b41787c59535b59333R1063).
> 
> I did the above as a temporary solution to INCR. Designing a signal from vmside to xside for the INCR is possible.

Ok, so the 300k test needs an update.

> For `test_002_clipboard_200k_truncated`, it is failing on `AssertionError: '' != 'test-inst-vm1'`. It should not do this. In this case, the new code truncates the `/run/qubes/qubes-clipboard.bin` and sets `/run/qubes/qubes-clipboard.bin.source` to ""

Right, the truncated one indeed should expect empty source. But I'm more worried about non-truncated one failing.

2024-10-24 15:11 UTC, alimirjamali commented
> But I'm more worried about non-truncated one failing.

I will look at test result again and see why it is failing. In the meantime, I am working with Marmarta on issue 9029 and will come back to this one very soon. Just for a change (classic c programming could grind mind)

2024-10-24 15:24 UTC, marmarek commented
It could be also a race condition in the test. I've added sleep(1) after sending ctrl+shift+c for now, lets see if that changes anything.

2024-10-24 16:52 UTC, alimirjamali commented
> According to the tests the copy operation for 64000 and more fails (with default config and increased limit too). I haven't found any error messages in logs (the metadata has copy_action=1, successful=1, cleared=1).

If this fails again, I appreciate if I could have the entire metadata. Is it possible? I am specifically interested on `protocol_version_...`, `buffer_size`. But others will be useful too.

2024-10-25 07:58 UTC, alimirjamali commented
> It could be also a race condition in the test. I've added sleep(1) after sending ctrl+shift+c for now, lets see if that changes anything.

I see that `test_002_clipboard_200k` is green. So it was indeed a race condition?

2024-10-25 10:21 UTC, marmarek commented
> I see that `test_002_clipboard_200k` is green. So it was indeed a race condition?

Yes, but a different one than I thought initially. Apparently zenity needs a bit of time to process "ctrl+c" when opened with a larger text.

2024-10-27 01:41 UTC, marmarek commented on gui-daemon/xside.c
> +        if (logging)
Lets leave like this now. Different ENOENT handling technically is a separate improvements not strictly related to this PR.

2024-10-27 01:41 UTC, marmarek approved these changes

2024-10-27 02:27 UTC, merged

2025-06-17 09:21 UTC, marmarek commented
On Tue, Jun 17, 2025 at 02:19:32AM -0700, Atrate wrote:
> Atrate left a comment (QubesOS/qubes-gui-daemon#150)
> 
> Is this configurable in r4.2 or only in r4.3?

Only R4.3.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab