Fix bugs in the icon-receiver
QubesOS/qubes-gui-daemon pull request #153
Opened 2024-10-17 11:30 UTC by qubest

2024-10-18 01:30 UTC, marmarek approved these changes

2024-10-18 01:31 UTC, marmarek requested changes

2024-10-18 01:31 UTC, marmarek commented on window-icon-updater/icon-receiver
> +            header_parts = header.decode('ascii').split(' ').restrip('\x00')
List doesn't have `restrip()` method. Did you mean `.rstrip()` just before `.split()` ?

2024-10-18 06:39 UTC, qubest commented on window-icon-updater/icon-receiver
> +            header_parts = header.decode('ascii').split(' ').restrip('\x00')
It is a typo sorry.

Yep, the rstrip should be added before split.
Or at header_parts[1].rstrip('\x00')

2024-10-18 10:30 UTC, marmarek commented on window-icon-updater/icon-receiver
> +            header_parts = header.decode('ascii').split(' ').restrip('\x00')
Better before split, as this is terminator of this whole header, not a specific part

2024-10-24 00:51 UTC, marmarek requested changes

2024-10-24 00:51 UTC, marmarek commented on window-icon-updater/icon-receiver
> +            header_parts = header.decode('ascii').restrip('\x00').split(' ')
```suggestion
            header_parts = header.decode('ascii').rstrip('\x00').split(' ')
```

2024-11-21 03:04 UTC, marmarek approved these changes

2024-11-21 04:10 UTC, merged