More protection vs override redirect windows
QubesOS/qubes-gui-daemon pull request #56
Opened 2020-12-01 03:20 UTC by DemiMarie

This adds two features:

- A flag to disable override redirect windows entirely.  This will break
  many applications.
- A distance that any window must have from the top of the screen.  This
  prevents an override redirect window from drawing over the taskbar
  from the GUI domain.

2020-12-01 04:16 UTC, marmarek requested changes
Some high-level comments:
 - you proposed `--override-redirect=disabled` option in https://github.com/QubesOS/qubes-issues/issues/4705#issuecomment-734500852 - IMO better to start with this option, even if only one version is implemented for now - it will avoid deprecating old option when we get more variants
 - instead of `taskbar_height` like now (which covers only taskbar at the top case), better use a generic way to avoid covering panel(s), wherever it is; I think that's [`_NET_WORKAREA` property  of the root window](https://specifications.freedesktop.org/wm-spec/1.4/ar01s03.html)

2020-12-01 13:16 UTC, marmarek commented
PipelineRetry

2020-12-02 03:13 UTC, DemiMarie commented
> * instead of `taskbar_height` like now (which covers only taskbar at the top case), better use a generic way to avoid covering panel(s), wherever it is; I think that's [`_NET_WORKAREA` property  of the root window](https://specifications.freedesktop.org/wm-spec/1.4/ar01s03.html)

How do I read this?  I can’t figure out what flags I should pass to `XGetWindowProperty`.  The documentation indicates that it is a `CARDINAL[][4]/32` but I have no idea what that refers to.

2020-12-02 03:39 UTC, DemiMarie commented
Also, can I assume `_NET_WORKAREA` to be a constant?

2020-12-02 04:15 UTC, marmarek commented
> How do I read this? I can’t figure out what flags I should pass to `XGetWindowProperty`. The documentation indicates that it is a `CARDINAL[][4]/32` but I have no idea what that refers to.

format = 32
long_length = some reasonable size for 4*number of workspaces - for example 64 (if too small, you will need to retrieve the reset with a second call)
req_type = XA_CARDINAL
property = `XinternAtom(g->display, "_NET_WORKAREA", False)`

See `process_xevent_propertynotify` function for example usage, including retrieving log value.

> Also, can I assume `_NET_WORKAREA` to be a constant?

No, user can move/resize panel(s). But you can easily get notification when it gets changed - like in `process_xevent_propertynotify`. Subscribe for properties changes on the root window with `XSelectInput()` (also already used in the code, but not on the root window).

Theoretically this also means, you'll need `_NET_CURRENT_DESKTOP`. But IMO it is quite safe to assume every workspace have the same areas (which you can also verify) and you can simply use the first one.

2020-12-03 04:47 UTC, DemiMarie commented
So my current plan is to use `_NET_CURRENT_DESKTOP` to determine the correct offset in `_NET_WORKAREA` to use.  Since a user could have multiple monitors, the workspaces cannot (IMO) be assumed to have the same area.  Fortunately, out of bounds offsets are just an error, not undefined behavior, so I am not too worried there.

How important is watching for property changes rather than re-fetching property values?

2020-12-03 04:53 UTC, marmarek commented
IIUC this gets called only for override-redirect windows (which rarely move), right? In that case, I think re-fetching may be ok.

2020-12-03 05:29 UTC, DemiMarie commented
Correct.  I can’t test this code locally at all, and am no expert on either the GUI daemon or X11.  Therefore, I strongly desire to keep the code as simple and obviously correct as possible, to minimize the chance that a bug will get through.

If possible, I would prefer that this code be tested before it goes live.  I can try to test it on the test machine, but it will take me a while to set it up.

2020-12-03 23:52 UTC, marmarek requested changes

2020-12-03 23:52 UTC, marmarek commented on gui-daemon/xside.c
> +            current_desktop, 4, False, XA_CARDINAL, &act_type, &act_fmt,
```suggestion
            current_desktop * 4, 4, False, XA_CARDINAL, &act_type, &act_fmt,
```

2020-12-03 23:52 UTC, marmarek commented on gui-daemon/guid.conf
> +  # taskbar_height = 20
This also needs an update.

2020-12-04 03:17 UTC, marmarek commented
CI:
```
DEBUG: xside.c:447:18: error: 'desktop_coordinates_size' defined but not used [-Werror=unused-const-variable=]
DEBUG:   447 | static const int desktop_coordinates_size = 4;
DEBUG:       |                  ^~~~~~~~~~~~~~~~~~~~~~~~
DEBUG: cc1: all warnings being treated as errors
```

2020-12-04 17:37 UTC, marmarek requested changes

2020-12-04 17:37 UTC, marmarek commented on gui-daemon/xside.c
> +    g->wm_workarea = intern_atom(g, "_NET_WORKAREA", True);
`True` here makes it fail hard if `_NET_WORKAREA` is not supported by the WM.

And BTW we do have such case - with hybrid GUI domain, where gui-daemon in dom0 for sys-gui is launched without window manager at all, and from dom0's Xorg point of view, there is just one fullscreen window.

2020-12-06 04:32 UTC, marmarek commented on gui-daemon/xside.c
> +            execl(QREXEC_CLIENT_PATH, "qrexec-client", "-tT", "-d", domid_str, service_call, (char*)NULL);
`-t` here breaks unicode characters in clipboard data.

2020-12-06 16:25 UTC, DemiMarie commented on gui-daemon/xside.c
> +            execl(QREXEC_CLIENT_PATH, "qrexec-client", "-tT", "-d", domid_str, service_call, (char*)NULL);
oops :laughing:, fixed by only using `-T`.  Also, this is broken with a GUI domain outside of dom0.

2020-12-07 02:24 UTC, marmarek commented on gui-daemon/xside.c
> +            execl(QREXEC_CLIENT_PATH, "qrexec-client", "-tT", "-d", domid_str, service_call, (char*)NULL);
In fact, clipboard looks to be broken with GUI domain even when using standard method, not qrexec. Because gui-daemon still tries to consult qrexec policy.

2020-12-07 02:32 UTC, DemiMarie commented on gui-daemon/xside.c
> +            execl(QREXEC_CLIENT_PATH, "qrexec-client", "-tT", "-d", domid_str, service_call, (char*)NULL);
And it must consult qrexec policy ― that’s why `qubes.ClipboardPaste` exists.  Hard-coding it to `@anyvm @anyvm ask` is not a good idea.

2020-12-07 03:53 UTC, marmarek approved these changes

2020-12-08 00:46 UTC, merged

2020-12-12 06:42 UTC, iamahuman commented on gui-daemon/xside.c
> +        border_y = border_width + g->work_y,
This should be `border_height`