Call policy.EvalSimple when outside of dom0
QubesOS/qubes-gui-daemon pull request #59
Opened 2021-05-04 02:17 UTC by DemiMarie

Outside of dom0, `qrexec-policy` is not available, but we can use
`qrexec-client-vm` and the `policy.EvalSimple` service instead.

2021-05-04 23:19 UTC, marmarek commented
This fails to build - see CI

2021-05-19 21:03 UTC, DemiMarie commented
This should now work in all cases, when combined with QubesOS/qubes-core-qrexec#69.  I changed the code so that it just connects to the `policy.Eval` socket if it is in dom0.

2021-05-23 12:46 UTC, marmarek commented
Tests:
```
May 23 00:58:38 dom0 qrexec-policy-daemon[1252]: b'policy.EvalSimple': invalid data from qube
```

2021-05-23 16:31 UTC, DemiMarie commented
> Tests:
> 
> ```
> May 23 00:58:38 dom0 qrexec-policy-daemon[1252]: b'policy.EvalSimple': invalid data from qube
> ```

I will try to reproduce this.

2021-05-25 13:46 UTC, marmarek commented
The dom0 case works now!

But the guivm doesn't (https://openqa.qubes-os.org/tests/17944). `guid.personal.log` from inside sys-gui:
```
dup2: Resource temporarily unavailable
recv: Connection reset by peer
```
And I don't see it made to the qrexec-policy-daemon.

2021-05-25 13:49 UTC, DemiMarie commented
> The dom0 case works now!
> 
> But the guivm doesn't (https://openqa.qubes-os.org/tests/17944). `guid.personal.log` from inside sys-gui:
> 
> ```
> dup2: Resource temporarily unavailable
> recv: Connection reset by peer
> ```
> 
> And I don't see it made to the qrexec-policy-daemon.

:woman_facepalming: `dup2()` returns the new file descriptor on success, not 0.  Easy fix.

2021-05-26 08:57 UTC, marmarek commented
GUIVM case:
```
qrexec-client-vm: unrecognized option '--@adminvm'
usage: qrexec-client-vm [options] target_vmname program_ident [local_program [local program arguments]]
Options:
  --buffer-size=BUFFER_SIZE - minimum vchan buffer size (default: 64k)
  -t, --filter-escape-chars-stdout - filter non-ASCII and control characters on stdout (default if stdout is a terminal)
  -T, --filter-escape-chars-stderr - filter non-ASCII and control characters on stderr (default if stderr is a terminal)
  --no-filter-escape-chars-stdout - opposite to --filter-escape-chars-stdout
  --no-filter-escape-chars-stderr - opposite to --filter-escape-chars-stderr
  --agent-socket=PATH - path to connect to, default: /var/run/qubes/qrexec-agent
recv: Connection reset by peer
```

But also, the gui daemon was terminated. Lets to it this way: for each `exit()` you add, accompany it with a comment why it is absolutely impossible or undesirable to recover from this situation - otherwise remove the `exit()` and add graceful recovery.

2021-05-26 16:17 UTC, DemiMarie commented
> GUIVM case:
> 
> ```
> qrexec-client-vm: unrecognized option '--@adminvm'
> usage: qrexec-client-vm [options] target_vmname program_ident [local_program [local program arguments]]
> Options:
>   --buffer-size=BUFFER_SIZE - minimum vchan buffer size (default: 64k)
>   -t, --filter-escape-chars-stdout - filter non-ASCII and control characters on stdout (default if stdout is a terminal)
>   -T, --filter-escape-chars-stderr - filter non-ASCII and control characters on stderr (default if stderr is a terminal)
>   --no-filter-escape-chars-stdout - opposite to --filter-escape-chars-stdout
>   --no-filter-escape-chars-stderr - opposite to --filter-escape-chars-stderr
>   --agent-socket=PATH - path to connect to, default: /var/run/qubes/qrexec-agent
> recv: Connection reset by peer
> ```

Fixed (missing comma)

> But also, the gui daemon was terminated. Lets to it this way: for each `exit()` you add, accompany it with a comment why it is absolutely impossible or undesirable to recover from this situation - otherwise remove the `exit()` and add graceful recovery.

That is a good approach!

2021-05-26 18:10 UTC, DemiMarie commented
PipelineRetry

2021-05-27 09:12 UTC, marmarek commented
```
Operation refused by dom0
qrexec-client-vm failed
```
But no info from the policy daemon.
I guess it's time for a proper review, instead of a poor approximation of test driven development ;)

2021-05-27 15:41 UTC, DemiMarie commented
> ```
> Operation refused by dom0
> qrexec-client-vm failed
> ```
> 
> But no info from the policy daemon.
> I guess it's time for a proper review, instead of a poor approximation of test driven development ;)

Sorry about this.  I would like to hope that my code is normally better than this 🙂.

2021-05-28 02:10 UTC, marmarek commented on gui-daemon/xside.c
> +                    "@adminvm", "policy.EvalGUI+ClipboardPaste", NULL);
This one still doesn't use the macro (and is wrong).

2021-05-28 03:00 UTC, DemiMarie commented on gui-daemon/xside.c
> +                    "@adminvm", "policy.EvalGUI+ClipboardPaste", NULL);
Oops!  That is the last one, thankfully.

2021-05-29 00:26 UTC, marmarek requested changes

2021-05-29 00:26 UTC, marmarek commented on gui-daemon/xside.c
> +    memcpy(buf + source_vm_len + 1, g->vmname, dst_vm_len);
I think you got this right, but I'd still prefer `sprintf`, for readability (you'll need to make `buf` 1 byte longer for that). And you can send one byte less below, to avoid sending extra NUL char.

2021-05-29 00:26 UTC, marmarek commented on gui-daemon/xside.c
> +        abort(); // cannot happen
This is really not a reason for crashing the whole process... Simply close the FD and treat as policy denial (after reporting the error).

2021-05-29 00:26 UTC, marmarek commented on gui-daemon/xside.c
> +            abort(); /* cannot happen per man page */
Again, there is no need to crash here. In fact, this can (and do) happen - various socket families can define additional error codes - and I hit `ECONNRESET` here already.

2021-05-29 00:26 UTC, marmarek commented on gui-daemon/xside.c
> +        return true;
For future extensibility, can we compare a prefix (including `\n`) only?

2021-05-29 01:39 UTC, DemiMarie commented on gui-daemon/xside.c
> +        return true;
Sure.

2021-05-29 01:39 UTC, DemiMarie commented on gui-daemon/xside.c
> +        abort(); // cannot happen
Fixed

2021-06-18 03:35 UTC, marmarek approved these changes

2021-06-18 03:44 UTC, merged