Move XInternAtom calls to startup
QubesOS/qubes-gui-daemon pull request #61
Opened 2021-05-25 13:57 UTC by DemiMarie

This should make some operations a little bit faster.

2021-05-30 15:44 UTC, marmarek requested changes

2021-05-30 15:44 UTC, marmarek commented on gui-daemon/xside.c
> +        if (!XInternAtoms(g->display, (char **)names, QUBES_ARRAY_SIZE(atoms_to_intern), 1, labels)) {
`only_if_exists` param should be `False`, not `1`. Have you tried to run this?

2021-06-01 15:18 UTC, DemiMarie commented on gui-daemon/xside.c
> +        if (!XInternAtoms(g->display, (char **)names, QUBES_ARRAY_SIZE(atoms_to_intern), 1, labels)) {
No, but I probably should before asking you to review it :woman_facepalming:.

2021-06-01 22:27 UTC, DemiMarie commented
Tested (and working) on the test laptop.

2021-06-18 02:58 UTC, marmarek approved these changes

2021-06-18 03:44 UTC, merged