Avoid dangerous functions in shmoverride
QubesOS/qubes-gui-daemon pull request #62
Opened 2021-05-25 23:43 UTC by DemiMarie

sprintf() is just a bad idea.

2021-05-29 03:44 UTC, DemiMarie commented
PipelineRetry

2021-05-30 15:37 UTC, marmarek requested changes

2021-05-30 15:37 UTC, marmarek commented on shmoverride/shmoverride.c
> +    if ((unsigned)(len = snprintf(idbuf, "%d", local_shmid)) >= sizeof idbuf)
For `snprintf`, you need to actually add the size parameter.

2021-06-01 21:39 UTC, DemiMarie commented
PipelineRetry

2021-06-18 02:59 UTC, marmarek approved these changes

2021-06-18 03:44 UTC, merged