Avoid rogue screen locking
QubesOS/qubes-gui-daemon pull request #63
Opened 2021-06-05 22:16 UTC by DemiMarie

by setting the _NET_WM_USER_TIME property when needed.

Fixes #3727.

2021-06-18 03:24 UTC, marmarek requested changes

2021-06-18 03:24 UTC, marmarek commented on gui-daemon/xside.c
> +                    fputs("_NET_WM_USER_TIME_WINDOW supported, but not found on the root window?\n",
I think you got the spec wrong. It should be set on application's window(s), not on the root window.
See https://specifications.freedesktop.org/wm-spec/1.4/ar01s05.html

Spec gives two options:
 - setting `_NET_WM_USER_TIME` directly on the application window (then update_wm_user_time should operate on the window where the event arrived)
 - setting `_NET_WM_USER_TIME` on a separate window, pointed with `_NET_WM_USER_TIME_WINDOW` (if window manager supports it) - in this case, gui-daemon would need to create separate stub window to set this property on (that window doesn't need to be mapped), I think it should be fine to use one stub window per gui-daemon and let all windows of that gui-daemon to point at it with `_NET_WM_USER_TIME_WINDOW`.

2021-06-18 03:24 UTC, marmarek commented on gui-daemon/xside.c
> +    update_wm_user_time(g, ev->time);
I'm not sure about this one. I think this is allowed according to the spec, but this will spam with PropertyChange events a lot. And indeed some random choice of applications (xfce4 terminal, gnome terminal, firefox) do not update the user time property on mouse movement, only on key presses + clicks.

2021-06-18 04:13 UTC, DemiMarie commented on gui-daemon/xside.c
> +                    fputs("_NET_WM_USER_TIME_WINDOW supported, but not found on the root window?\n",
That makes more sense!  I misread the specification and thought that setting `_NET_WM_USER_TIME_WINDOW` was the window manager’s job.

2021-06-18 04:13 UTC, DemiMarie commented on gui-daemon/xside.c
> +    update_wm_user_time(g, ev->time);
The purpose of this is to detect scroll events, which otherwise are not detected.

2021-06-18 14:29 UTC, marmarek commented on gui-daemon/xside.c
> +    update_wm_user_time(g, ev->time);
Scroll is in fact a mouse button press in X11 (buttons 4 and 5 for up/down).

2021-06-24 01:32 UTC, marmarek commented
You need to set `_NET_WM_USER_TIME_WINDOW` on app windows, pointing at `g->time_win` (if supported and created).

2021-06-25 00:18 UTC, marmarek approved these changes
Ok, now it seems correct. It is time for testing it now. AFAIR the proper test scenario for this is:
1. open some VM app
2. give it a focus, place mouse inside its window
3. do only clicks, not movements, not keyboard input
4. screen should _not_ lock after defined time (10 minutes by default)

Is that correct? Should the point 3 be about any clicks, or just scroll?

2021-06-25 00:36 UTC, DemiMarie commented
> Ok, now it seems correct. It is time for testing it now. AFAIR the proper test scenario for this is:
> 
> 1. open some VM app
> 2. give it a focus, place mouse inside its window
> 3. do only clicks, not movements, not keyboard input
> 4. screen should _not_ lock after defined time (10 minutes by default)
> 
> Is that correct? Should the point 3 be about any clicks, or just scroll?

I imagine so.  Can this be part of the integration tests on OpenQA?

2021-06-25 00:58 UTC, marmarek commented
> I imagine so. Can this be part of the integration tests on OpenQA?

That's exactly my intention.

2021-07-05 21:23 UTC, marmarek commented on gui-daemon/xside.c
> +        { &g->wm_current_desktop, "_NET_WM_CURRENT_DESKTOP" },
Rebase went wrong here.

2021-07-06 09:48 UTC, marmarek commented on gui-daemon/xside.c
> +        XFree(state_list);
This crashes on the first iteration.

2021-07-06 11:12 UTC, DemiMarie commented on gui-daemon/xside.c
> +        XFree(state_list);
Fixed, but not pushed yet, as I ran into a `BadValue` error.

2021-07-06 11:36 UTC, marmarek commented
> That's exactly my intention.

I've implemented it at https://github.com/marmarek/openqa-tests-qubesos/commit/e5ed6c5295fdb76e100f280e6e7124f94ea0f9f9. Without this PR, it fails as expected. I've tried to test with this PR, but ran into the issue above.

2021-07-06 12:43 UTC, DemiMarie commented
I think I have a fix, but please do not review the code yet, as I forgot to test it first.

2021-07-06 12:52 UTC, DemiMarie commented on gui-daemon/xside.c
> +        XFree(state_list);
Tested and working

2021-07-09 03:08 UTC, marmarek approved these changes

2021-07-09 03:21 UTC, merged