Use XCB for image handling to reduce use of shmoverride
QubesOS/qubes-gui-daemon pull request #65
Opened 2021-06-24 21:21 UTC by DemiMarie

This is very much a draft for several reasons, not least of which is that tray icon handling simply has not been (re)implemented yet.  I also have not tested any of this code, beyond ensuring it builds.  I also know that quite a bit of error handling is missing.  In short, this code is highly experimental and almost certainly buggy.  Nevertheless, I would appreciate a review.

2021-06-25 04:13 UTC, marmarek requested changes
I'm a bit worried about the number of issues in MFN-based mapping - the part that you won't test using R4.1-only parts (you need either template/standalone imported from R4.0, or Windows with QWT installed). Can you keep it unchanged, without complicating other places too much? I guess you'll need two cases in the `put_shm_image` wrapper, anything else?

2021-06-25 04:58 UTC, DemiMarie commented on gui-daemon/xside.c
> +        if (vm_window->shmid != -1) {
Whoops!  I had figured that out earlier, but missed this.  In practice it would just fail harmlessly, but it is still a bug.

2021-06-25 04:58 UTC, DemiMarie commented on gui-daemon/xside.c
> +            xcb_shm_detach(g->cb_connection, vm_window->shmseg),
Good point; will fix.

2021-06-25 04:58 UTC, DemiMarie commented on gui-daemon/xside.c
> +            "xcb_shm_detach");
I believe that detaching the segment *is* the destructor for `vm_window->shmseg`.  I will add the unmap ioctl call, though.

2021-06-25 04:58 UTC, DemiMarie commented on gui-daemon/xside.c
> +    vm_window->shmseg = xcb_generate_id(g->cb_connection);
I originally thought that was correct, but then realized that it generates file descriptors on the *server* and returns them to the client, which we do not want.  I am 99% certain that `xcb_generate_id` is correct here, judging by the Xlib source code.

2021-06-25 04:58 UTC, DemiMarie commented on gui-daemon/xside.c
> +    vm_window->shmseg = xcb_generate_id(g->cb_connection);
Answered below.

2021-06-25 04:58 UTC, DemiMarie commented on gui-daemon/xside.c
> +    shm_args->shmid = g->cmd_shmid;
Oops!

2021-06-25 04:58 UTC, DemiMarie commented on gui-daemon/xside.c
> +                                   g->gntdev_fd, true),
Yup :disappointed:.

2021-06-25 04:58 UTC, DemiMarie commented on gui-daemon/xside.c
> -        off) {
Can I compute `bytes_per_line` as the straightforward `vm_window->image_width * vm_window->image_height * 3`?

2021-06-25 04:58 UTC, DemiMarie commented on gui-daemon/xside.c
> +static void handle_window_dump_body(Ghandles *g,
A bit confused here.  Do you mean that 8ca7ebd50e86b5c24e9919036eb27cee5c0feb0d should be reverted, or something else?

2021-06-25 04:58 UTC, DemiMarie commented on gui-daemon/xside.h
> +    uint32_t offset;       /**< Offset that X server should call mmap() at */
Will do, in a separate commit.

2021-06-25 05:02 UTC, DemiMarie commented on gui-daemon/xen_ioctl.c
> +bool compute_gui_daemon_offset(int gntdev_fd,
Good point; I imagine that calling this several times would leak memory.

2021-06-25 05:11 UTC, DemiMarie commented on gui-daemon/xen_ioctl.c
> +            sizeof(struct ioctl_gntdev_grant_ref) && "grant computation would overflow");
This is intended to be defensive programming, but I can remove it if you want.

2021-06-25 06:19 UTC, DemiMarie commented
> I'm a bit worried about the number of issues in MFN-based mapping - the part that you won't test using R4.1-only parts (you need either template/standalone imported from R4.0, or Windows with QWT installed).

We should probably test this in OpenQA.

> Can you keep it unchanged, without complicating other places too much? I guess you'll need two cases in the `put_shm_image` wrapper, anything else?

I would prefer not to.  For one, it would _increase_ the amount of code only used by legacy qubes.  I suspect it would also require more code overall, and would increase our dependency on Xlib.  These changes allow us to remove our dependency on libXext entirely, for example.

2021-06-25 11:46 UTC, marmarek commented on gui-daemon/xside.c
> +static void handle_window_dump_body(Ghandles *g,
Yes, this.

2021-06-25 11:48 UTC, marmarek commented on gui-daemon/xside.c
> -        off) {
I think it's rather `vm_window->image_width * 4` because of padding.

2021-06-25 11:50 UTC, marmarek commented on gui-daemon/xside.c
> +    vm_window->shmseg = xcb_generate_id(g->cb_connection);
Then, something feels wrong here - you don't pass the shared mapping size to the X server anywhere.

2021-06-25 11:55 UTC, marmarek commented on gui-daemon/xside.c
> +    vm_window->shmseg = xcb_generate_id(g->cb_connection);
Or, maybe it is implicit via image dimensions?

2021-06-25 11:58 UTC, DemiMarie commented on gui-daemon/xside.c
> +    vm_window->shmseg = xcb_generate_id(g->cb_connection);
I believe the size is computed by the X server from the arguments to `xcb_shm_put_image`.  The server has no idea what the size of the mapping actually is; it just tries to map as much as it needs to fulfill the request.

2021-06-25 12:04 UTC, DemiMarie commented on gui-daemon/xside.c
> +    vm_window->shmseg = xcb_generate_id(g->cb_connection);
That is why the check that I originally removed is so important: without it, the server would blindly `mmap` grants that could easily belong to a different window, or maybe even a different qube (depending on how `/dev/xen/gntdev` works).

2021-06-25 13:56 UTC, fepitre commented
PipelineRefresh

2021-06-25 14:00 UTC, DemiMarie commented
PipelineRetry

2021-06-25 14:04 UTC, DemiMarie commented
Most of the intermediate commits won’t build due to dependency issues.  Should I rebase?

2021-06-25 14:05 UTC, fepitre commented
Yes, try to rebase and force push.

2021-06-25 14:07 UTC, DemiMarie commented
> Yes, try to rebase and force push.

To elaborate, they build fine locally, but are missing some build deps.

2021-06-26 07:21 UTC, DemiMarie commented
I kept getting `BadMatch` errors no matter what I tried on the client side.  I finally checked the X.Org Server source code, and found this:

```C
    if (fstat(fd, &statb) < 0 || statb.st_size == 0) {
        close(fd);
        return BadMatch;
    }

    shmdesc = malloc(sizeof(ShmDescRec));
    if (!shmdesc) {
        close(fd);
        return BadAlloc;
    }
    shmdesc->is_fd = TRUE;
    shmdesc->addr = mmap(NULL, statb.st_size,
                         stuff->readOnly ? PROT_READ : PROT_READ|PROT_WRITE,
                         MAP_SHARED,
                         fd, 0);

    close(fd);
    if (shmdesc->addr == ((char *) -1)) {
        free(shmdesc);
        return BadAccess;
    }
```

That is, the server rejects file descriptors pointing to files that appear to be empty, and `mmap()`s non-empty files in their entirety. 
 This is reasonable in the case of regular files, where sending a descriptor to an empty file is almost certainly a client bug, and where the size of the file determines how large the shared memory segment should be.

However, `/dev/xen/gntdev` is not a regular file!  It is a character device and therefore of course has size 0.  There is no way for the GUI daemon to set the size to something else, and the request has no other way to convey this information.  Theoretically, the X server could keep the file descriptor open and defer mapping it until `xcb_shm_put_image` is called, but that would require as-yet-unknown changes on the X server side.  And if we can change the X server, we can solve the problem properly: with a new extension that allows the client to specify the sizes.  Another alternative is to use the DRI3 extension and dma-bufs, but that would be both significantly more complex and involve less-tested kernel code.

2021-06-26 14:32 UTC, marmarek commented
That's a bummer :( But I'm not very surprised given lack of explicit mapping size parameter.

As for the DRI3, after a brief look at the protocol (and [a guide](https://keithp.com/blogs/dri3_extension/)), it seems to not be _that_ complex. The most interesting call is `DRI3PixmapFromBuffer`. But still more complex than just swapping SHM calls. I'm not sure about relation between `XImage` and `Pixmap` - DRI3 operates on pixmaps and we need to put them into a window somehow. Also, the DRI3Open returns an FD to the graphic device - we don't need that here, and I _hope_ nothing really requires the DMA-BUFs to be constructed from that device - otherwise, it will be useless for us...

One significant issue with DRI3 is that (I think) it requires a real graphics card present. Which means it won't work with our virtual GUI domain versions (the one with VNC - using dummy driver, or the one backed by gui-agent - using Xephyr).

If you want, you can give DRI3 a try (while waiting for Smithay), but given the above, shmoverride way needs to remain an option - in this approach you can't really replace it fully (even just for grants).

The worry about grant based dma-bufs maturity is warranted, but I think we'll need that at some point anyway, so we can start testing it already - before using it in any default setup.

2021-06-26 17:02 UTC, marmarek commented
I've looked at DMA-BUF userspace API, and it almost fits the need of `shm_attach_fd`. I think the only difference is the size discovery - Xorg tries to `fstat()`, while DMA-BUF expects `lseek(fd, 0, SEEK_END)` (and does not support `fstat()`). If that indeed is the only difference, it may be easier to adjust shmoverride (and sadly still require it even for grant maps with Xorg) to intercept `fstat()` to:
1. Execute real `fstat()` first
2. If it's a xen-gntdev character device (based on `st_mode` and `st_rdev`), fill the size field using `lseek()`

That won't allow getting rid of shmoverride, but it will allow start testing DMA-BUF, and may even be compatible with XWayland (with such shmoverride preloaded there too). This option could be preferred only because it doesn't require DRI3 extension, which we don't have in all the cases we use X server in.

2021-06-29 03:51 UTC, DemiMarie commented
Closing in favor of #69.

2021-06-29 03:51 UTC, closed without merging