Use XCB instead of Xlib for shared memory
QubesOS/qubes-gui-daemon pull request #67
Opened 2021-06-27 07:13 UTC by DemiMarie

Xlib does not support file descriptor passing or dma-bufs.  The GUI daemon does not currently use either of these, but it will in the future.  Switching from Xlib to XCB is a necessary first step in that direction.

This is a subset of #65: it includes the parts that can work without needing any changes to the X server or kernel.

2021-06-28 02:13 UTC, marmarek requested changes

2021-06-28 02:13 UTC, marmarek commented on gui-daemon/xside.c
> +        // shmctl(vm_window->shmid, IPC_RMID, 0);
This should not be commented out.

2021-06-28 02:13 UTC, marmarek commented on gui-daemon/xside.h
> +    uint32_t grants;       /**< Number of grants mapped */
Those two are unused, and likely won't be used with DMA-BUFs.

2021-06-28 02:13 UTC, marmarek commented on gui-daemon/xside.h
> +    int shmid;           /**< System V IPC identifier, or -1 for fd-passing */
The -1 case is not applicable in this version. But it may be, so it's ok to leave this comment (and actual handling of -1 in few places).

2021-06-28 15:56 UTC, DemiMarie commented
Everything I have tried works well.  Tray icons are not tested yet, and a Windows 7 qube keeps trying to snap back to full screen.  Not sure if that is normal.

2021-06-29 01:10 UTC, marmarek commented
> Windows 7 qube keeps trying to snap back to full screen. Not sure if that is normal.

It may be the case, yes.

2021-06-29 01:13 UTC, marmarek approved these changes

2021-06-29 05:58 UTC, DemiMarie commented
Tray icons work.

2022-10-03 19:20 UTC, closed without merging