Disable subwindows by default
QubesOS/qubes-gui-daemon pull request #86
Opened 2021-10-05 10:25 UTC by DemiMarie

The default GUI agent never creates them, and they are extra attack surface.  For instance, they are involved in one of the exploits for QSB#072.

2021-10-07 03:04 UTC, marmarek commented on gui-daemon/xside.c
> +    if (untrusted_crt.parent && !g->permit_subwindows) {
This is wrong check, because the gui-agent (unfortunately) sends the root window ID here for top-level windows.  You need to move it after the lookup of that window (see where I added the check for override-redirect subwindows).

2022-03-31 03:45 UTC, DemiMarie commented
@marmarek would you mind re-reviewing this?

2022-04-05 01:30 UTC, marmarek requested changes
Please add the option also to `guid.conf`, which serves as a documentation of supported options.

2022-04-06 01:23 UTC, marmarek approved these changes

2022-04-06 01:23 UTC, merged